### ISSUE TITLE
Android app freezing after launch

### ISSUE THREAD

**Issue by matejkramny** [immich-app/immich#10030]
### The bug

The android app freezes shortly after launching, every time. Perhaps I have too big of a library.. web works fine.
The app logs don't show anything useful.

I have tested the demo server, and it works fine.
Library is ~70k photos.
Another user on my server has ~10k photos - works without issue.

Have had an external library but removed since, don't think it's a duplicate of #8148 but is very similar.

How can I best figure out what's wrong?

### The OS that Immich Server is running on

Ubuntu 22 lts

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c",
"wal_compression=on"]
volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
# The location where your uploaded files are stored
UPLOAD_LOCATION=<redacted>
# The location where your database files are stored
DB_DATA_LOCATION=<redacted>
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>
# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=<redacted>
DB_DATABASE_NAME=<redacted>
```

### Reproduction steps

```bash
1. Have big library
2. open android client (logged in already)
3. App is interactive for ~10s
4. App freezes, perhaps for ~30s
5. Becomes responsive again but then freezes forever
6. Backgrounding and opening app then shows black screen (flutter crashed perhaps)
...
```

### Relevant log output

```shell
I can't find any relevant logs in the app
Have enabled more verbose + diagnostics. No logs after the black screen
```

**Comment by alextran1502** [comment]
Can you try accessing your instance over local IP? What is your mobile phone model?

**Comment by matejkramny** [comment]
Hi, I can't as it's a dedicated server in another country.
Using pixel 2. It's understandably not the best in today's performance but it works just fine with 10k photos user

**Comment by Mikesco3** [comment]
I'm having the same issue. 
My server is within my local network, I'm accessing it using the local static IP. 

I'm running a galaxy S21+

But it seems to be the issue with my android app version 1.106.3 build 14.3

Server version 1.106.4 on a Debian 12 container.

The experience is that:

1. Open the app 
2. If I scroll a bit or try to play a video, then at around 30 seconds into it, the app freezes and doesn't respond to anything, except if I hit the button on my phone to switch to another app, (not even backing all the way out to another app, just enough to show me the carousel of other running apps) and then go back to Immich then it might snap out of it after about a 3-5 second blank screen but about 10 - 30 seconds later lock up again. 
3. But most of the time I can only get it back by closing Immich and starting again.

I've tried running it in various conditions: 
Closing all other apps
Rebooting the phone
But same result, seems to be pretty consistent. 

It feels like it locks up trying to index or cash the content.

I also very large library.
Also the app doesn't tell me anymore how many total items...

Let me know how else I can help. 
Thank you for such an awesome app!!
Look Forward to contributing and paying some

**Comment by matejkramny** [comment]
I'm going to try to attach adb to the app loaded on my phone and will see what's locking it up later this week.
Can't reproduce the hanging in the emulators but I'm suspecting it's writing a lot of data to the database?

**Comment by matejkramny** [comment]
I wonder if it would be worth implementing this usage pattern, if not already - https://isar.dev/recipes/multi_isolate.html#example

I found isolate usage in the code but it might be for the background sync. I'm thinking if doing the database sync in an isolate thread would help with performance.
For a large library I imagine 70k record updates would take a while whilst it freezes the UI thread

**Comment by matejkramny** [comment]
Hi,

I found using isolates helped, adb logs don't show any more than usual, other than using CPU profiling which shows Isar doing this:

![image](https://github.com/immich-app/immich/assets/797608/5de6044a-b5e5-4467-8084-cf089d57301c)
![image](https://github.com/immich-app/immich/assets/797608/a0e6cf9c-558b-4059-a660-27f6a0fa1198)
![image](https://github.com/immich-app/immich/assets/797608/551b9680-eebb-4f94-8087-152d80fb2cc5)

The UI locks up at this state, and there are no more logs.

Doing more CPU profiling shows about the same things, maybe as flutter itself stops responding on the app.
It's possible something crashes, but I'm at a loss as to how to debug it any further because there are no logs in addition to what I screenshotted.

As I mentioned, running the app with my isolate PR fixes this problem, but I suspect it might be something _related_ to it, or a side effect/bug that I put in f.e. - there are watchers on the Isar db that would refresh the UI. Perhaps this happens too many times (per asset?) and that might/not be happening with the assets synced in the isolate?

Thank you!

**Comment by AleXburnA** [comment]
We‘re experiencing the same on my wife’s Galaxy S21, see here: https://github.com/immich-app/immich/discussions/9614

I hope your PR can be merged at some point. For us, this is the most annoying bug with this otherwise amazing software. I understood it might not be the root cause, but maybe it improves things. I am clutching at every straw 🤣

**Comment by dsimoes** [comment]
Hey!

I've implemented immich locally for a month now. Everthing has being going great up until a few days ago?
For some reason the App opens, I can see the thumbnails loading and then It just hangs, can't scroll ou access the menus.

Android App version: 1.115.0
Immich version (updated today): v1.115.0
Phone: Samsung A53 5G

I've tried clearing cache: same behaviour.
I've proceeded clearing data. This required me to login again and setup automatic backup. So far the app is working, will report back if not.

**Comment by alextran1502** [comment]
@LinhyCZ how many assets do you have on your instance and local device? How many album do you have on your Immich instance? How long have you been installing the app?

**Comment by matejkramny** [comment]
@alextran1502 is there a good way to get library stats? I've made a dummy user with 100k photos and the app worked just fine. My library is ~70k + some videos

Also tested on pixel 2 when i made this issue (100% of the time), now got a pixel 8 pro - still having the same problem just not as frequently

**Comment by alextran1502** [comment]
@matejkramny the easiest way is from the web, you can hover on the icon next to the navigation button to show how many assets/albums the user has. I believe the bottleneck is our albums synchronization code that competes with the UI thread. We discussed internally and come up with a better solution. The PRs you are seeing that refactoring the mobile app are steps toward solving this issue

**Comment by LinhyCZ** [comment]
@alextran1502 I have about 24k photos and 2k videos + 10k assests from external library. I have been using Immich for almost a year (I think :D), about two months ago I noticed some assets were not uploaded, so I uninstalled the app, installed it again and reran the upload job (which fixed the missing assets).

**Comment by alextran1502** [comment]
@LinhyCZ thanks for the info. How many Immich's albums and albums on the local device do you have?

**Comment by LinhyCZ** [comment]
@alextran1502 I only clicked on the Recent option, I don't have any albums created..

**Comment by LinhyCZ** [comment]
@alextran1502 I have tried working with the app a bit more, uninstalled it and installed it back again and it is somewhat working, but the reactions are very slow.. sometimes it takes about 30 seconds until the app registers i clicked on something or renders something..

**Comment by alextran1502** [comment]
@LinhyCZ We are working toward a better sync operation, which will make the app more responsive when first opening. By the way, what is your phone model?

**Comment by LinhyCZ** [comment]
@alextran1502 Might make it better, but this is not just on a first opening. For me the app is very sluggish the whole time I use it.

My phone is an old Huawei Mate 10 Pro.

**Comment by yewkay** [comment]
I have 63k photos and I'm experiencing the same app hang/crash issue. Background sync works but if I open the app, it will crash shortly. 

Opening in webui will works fine for me

**Comment by jetblack-nz** [comment]
Hi, not sure this is supposed to be Android specific, just noting that I experience the same with 55k images on a new iPhone. The app freezes regularly after opening.

**Comment by Matou25** [comment]
@alextran1502  Hi, I previously post in [https://github.com/immich-app/immich/issues/11113#issuecomment-2384273824](url)
but my issue is more this one .
 i have systematic crash of android app after around 24sec on huawei P30pro and S21+:
- open immich 
-  scrool up and down 
- after 15s 1st freeze during 1 or 2s 
- 18s second freeze
- 24s app freeze definitively, need to force close

 I find something interessting this morning, app don't crash and is very smooth if I follow this step:
- put phone in fly mode
- start immich
- wait 2-5s 
- disable fly mode

it work until i force app to close in android menu

**Comment by alextran1502** [comment]
@Matou25 what is the stats of your account? How many assets, how many albums?

**Comment by Matou25** [comment]
@alextran1502  ![image](https://github.com/user-attachments/assets/824b4957-269b-4447-ac68-8a8b36255188)
it's an external library 
for now 10 albums ( working on create more base on my folder tree)

**Comment by ThomasConrad** [comment]
Have the same issue with about 33k images. Have to force reboot entire phone to escape it.

**Comment by slagiewski** [comment]
I have the same issues with about 50k images. Galaxy s20 fe

**Comment by Matou25** [comment]
> @ThomasConrad @slagiewski Can you guys try not selecting any album for backup and open the app, so that it loads the remote only assets and see if it is still crashing

Hi @alextran1502, 
To add information my account is admin account. 
I dont use backup function

**Comment by matejkramny** [comment]
Hi @alextran1502, the latest app update have made things a lot more stable, as in I am no longer seeing the app freezing and is much smoother than before.
Running 1.20.1

I'm happy to close this issue but perhaps others who also experienced this can confirm it's gone too?

**Comment by Matou25** [comment]
@matejkramny even with 1.120.1 build166 it's the same for me, app continue to freeze
server is in 1.120.2

**Comment by alextran1502** [comment]
There is nothing that changes @matejkramny. Perhaps you were connecting through the local IP so the sync process is faster?

**Comment by LinhyCZ** [comment]
Just to add some my recent findings - This happens only on my older phone Huawei Mate 10 Pro, my GF's Pixel 7 is working all good and she has huge (like 10x bigger than mine) library. 

I've noticed, that I just have to sit through the sync at the beginning and after that it works great. 
It starts working after 
`| INFO     | AssetNotifier        | Load assets: 186936ms |`
Appears in the log. 

What is interesting to me (maybe it's fine, I have no clue how the sync process worked) is these lines in log
`2024-10-01 16:39:43.004103 | INFO     | SyncService          | Added a new local album to DB: Camera |
2024-10-01 16:39:42.691853 | INFO     | SyncService          | Upserted 7025 assets into the DB |
2024-10-01 16:39:41.821461 | INFO     | SyncService          | 8 assets already existed in DB, to upsert 7025 |
2024-10-01 16:39:06.896311 | INFO     | SyncService          | Syncing a new local album to DB: Camera |`

I used Immich multiple times before on my device. Why does it load all the images to DB again? (And takes over 30 seconds)

But again, maybe it should work like that and the only issue is the sync mechanism that is being worked on. (Thank you very much for that, btw :))

**Comment by BitcoinCode** [comment]
I've tried to clear the cache but this didn't work, then I uninstalled the app and reinstalled, it seems that the issue is fixed at least for now.

**Comment by spikeygg** [comment]
> Can you guys try not selecting any album for backup and open the app, so that it loads the remote only assets and see if it is still crashing

Hi @alextran1502,

I also have this issue. It seems to be unrelated to the sync operation. I can see the spinner at the bottom left spinning sporadically (stop and go) but it finishes and the UI still has poor response for several seconds. I turned off the folders and closed the app and relaunched it and the sluggish UI performance persisted. I then went in and turned off sync and did the close/reopen again and it still didn't improve. 

I  have three Android devices that I tested: 
1. Google Pixel 4 XL takes ~45 seconds until the UI works smoothly (1591 local photos, this is the device I tested with sync turned off) 
2. Samsung Galaxy Tab S7+ takes ~20 seconds until the UI responds smoothly (479 photos, sync on)
3. Samsung Galaxy Tab A7 takes ~1:30 until the UI responds smoothly (10 photos, sync on)

I think it has a lot to do with the processing power of the device because it seems to follow that. I'm not sure what the app is doing during launch but there is absolutely no UI indication that it is working on stuff while the response is sluggish.

**Comment by yewkay** [comment]
I doubt it's the processing power. I have the S25 ultra, fastest chip on the block for android and it still happens to me.

I uninstalled and reinstalled the app and still happens

**Comment by spikeygg** [comment]
> I doubt it's the processing power. I have the S25 ultra, fastest chip on the block for android and it still happens to me.

Sorry, I didn't mean to suggest that it's processing power that causes the problem but it is definitely related to the problem. Whatever the device is doing on immich launch takes a specific amount of processing and slower devices take much longer to complete the crunch.

**Comment by TheekshanaA** [comment]
Yep, can confirm I've got the same issue on Android with my S21 Ultra. Works completely fine on mobile. I have got prefer remote images enabled too

**Comment by spikeygg** [comment]
I launched the app this morning and I had taken several photos the day earlier but had charged my phone over night. I assume that the photos were already uploaded to my server overnight because I watched for the notification of uploads and it never appeared. The set of photos at the top had the cloud icon **without the checkbox** and the app was sluggish until the cloud icon was populated with a checkbox.

Based on this experience, I think the Immich photo sync verification function must be causing the poor user interface response on the Android app. Maybe you guys already knew that but I just figured it out. 😊

**Comment by TheekshanaA** [comment]
> I launched the app this morning and I had taken several photos the day earlier but had charged my phone over night. I assume that the photos were already uploaded to my server overnight because I watched for the notification of uploads and it never appeared. The set of photos at the top had the cloud icon **without the checkbox** and the app was sluggish until the cloud icon was populated with a checkbox.
> 
> Based on this experience, I think the Immich photo sync verification function must be causing the poor user interface response on the Android app. Maybe you guys already knew that but I just figured it out. 😊

Yep, I'm fairly confident this is related as well as I noticed similar behaviour.

**Comment by bashir-abdelwahed** [comment]
does reverting to a previous APK version help ?
