### ISSUE TITLE
immich-cli --recursive "No files found"

### ISSUE THREAD

**Issue by midiwidi** [immich-app/immich#10380]
### The bug

Uploading folders using immich cli recently stopped working
```
immich upload --dry-run --album-name 'Weihnachten 2016' --recursive 'Weihnachten_2016\'
Crawling for assets...
No files found, exiting
```
I was using the exact same command many times before successfully. The folder definitely contains JPG files
```
dir Weihnachten_2016\

    Directory: D:\Bilder\Privat\Weihnachten_2016

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          16.06.2024    14:05        5594765 P1030855.JPG
-a---          21.12.2016    04:20       12044240 P1030860.MP4
-a---          16.06.2024    14:05        5685863 P1030861.JPG
-a---          16.06.2024    14:05        5652859 P1030862.JPG
-a---          16.06.2024    14:05        5461499 P1030863.JPG
-a---          16.06.2024    14:05        4525403 P1030866.JPG
...
```
I also tried different ways of specifying the folder / files such as
'.\Weihnachten_2016\\', 'Weihnachten_2016\\\*', '.\Weihnachten_2016\\\*.JPG' but nothing worked.
What does work is specifying a specific file
```
immich upload --dry-run --album-name 'Weihnachten 2016' --recursive '.\Weihnachten_2016\P1030855.JPG'
Crawling for assets...
Checking files | ████████████████████████████████████████ | 100% | ETA: 0s | 1/1 assets
Found 1 new files and 0 duplicates
Would have uploaded 1 asset (5,6 MB)
Would have created 1 new album
Would have updated albums of 1 asset
```

I updated the cli using `npm update -g` before I tried uploading. The version I have is 2.2.4
```
npm list -g
C:\Users\midiwidi\AppData\Roaming\npm
+-- @immich/cli@2.2.4
`-- npm@10.8.1
```

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not applicable
```

### Your .env content

```Shell
not applicable
```

### Reproduction steps

```bash
run immich cli to upload a folder recursively
```

**Comment by fky2015** [comment]
related to #10430

**Comment by lipe123** [comment]
Please can we get the fix approved/merged or something, I just started using immich and i have soo many images i wish to import with the CLI. The only thing that works is importing one image at a time, none of the directory or any recursive functions work on windows.

**Comment by midiwidi** [comment]
Could we downgrade the immich cli to an older version (while this is fixed) in which --recursive was working or is that not possible due to the changes in the immich server? If so, which version should we downgrade to?
Another option could be to run the cli in WSL.

**Comment by alextran1502** [comment]
The fix has been merged #10430 and will be available in the next release which will be sometimes next week!

**Comment by stephenjoly** [comment]
I am still experiencing this exact issue on v1.111.0

❯ immich -V #immich cli version                                                                                                                                                                               
2.2.13                                                                                                                                                                                                               
❯ npm -v                                                                                                                                                                                 
10.8.2                                                                                                                                                                                                               
❯ nvm -v                                                                                                                                                                                  
0.39.7                                                                                                                                                                                                               
❯ node -v                                                                                                                                                                                
v20.16.0

**Comment by lipe123** [comment]
I feel like you are supposed to do ./icloud_backup_preserved for your path or specify the whole path maybe?

Idk, I recently imported all my stuff in windows and it was working for me then.

**Comment by stephenjoly** [comment]
@lipe123  thanks for the reply! This code should work, I did try with the full path with the same result. 

I tried the exact same process on Windows and it worked no problem. Wondering if this is still an active bug for Ubuntu Server 24.04.

**Comment by pavichokche** [comment]
I just ran into this issue when using the latest Immich version and latest CLI version (as of October 17 2025) while using the CLI in Windows 11 PowerShell (Node JS 25, installed with nvm).
My command was initially this, since I was using Tab to auto-complete/suggest folder names while preparing the command:

immich upload --dry-run --recursive 'G:\Photos and Videos\Phone Photos\Samsung S6\\'

However this caused the 'No files found, exiting' issue. The solution? Remove the very last \ at the end. Immediately the command ran successfully and found all images/videos contained within all the subdirectories :D
