### ISSUE TITLE
Web timeline jumps back to the wrong place after viewing asset on detailed view - Firefox

### ISSUE THREAD

**Issue by elversoee** [immich-app/immich#10847]
### The bug

i was looking for at specific Asset on my Immich Instance, that i almost knew the date it was taken so logging in and scrolling back on the timeline to find the date range and found the asset. when i was finished with the asset i normally use the "ESC" key on my keyboard to go back to the timeline but for what ever reason the returned timeline is not on the right place anymore it is jumping usually back anywhere from 14 days to several months back but not always, it seems to only be related to Firefox and i have tried to delete cookies/cache that do not seem to do anything and testing with Brave browser do not seem to have the Issue

### The OS that Immich Server is running on

Proxmox Dockge LXC

### Version of Immich Server

1.107.2

### Version of Immich Mobile App

1.107 build.146

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: null
  model-cache: null
networks: {}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=xxxxxxxxxxx
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Logging in to Immich web using Firefox 126 
2.I was looking for at specific Asset on the timeline 
3.Clicking to view detailed view 
4.finished looking at the asset
5.Using "ECS" key to go back to timeline
6.sometimes the timeline is at the wrong place when going back between 14 days and several months
```

### Additional information

I have not seen this bug on my system before 1.107.2 and it seems Brave Browser works and Mobile App on Android also works

**Comment by bo0tzz** [comment]
This will be resolved by #10646

**Comment by SwallowYourDreams** [comment]
This also affects the mobile client on Android.

**Comment by alextran1502** [comment]
resolved in #12042 as well

**Comment by xRealNeon** [comment]
Still having this issue. I am on the newest version. Also when resizing the browser window the timeline jumps.
