### ISSUE TITLE
Immich Server stopped working on linux-arm64 with v1.109.0

### ISSUE THREAD

**Issue by bmachek** [immich-app/immich#11189]
### The bug

Immich server fails to start with following error in the logs on arm64.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.109.0

### Version of Immich Mobile App

v1.108.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    environment:
      DISABLE_JEMALLOC: true

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    environment:
      DISABLE_JEMALLOC: true

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always
    environment:
      DISABLE_JEMALLOC: true


  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      DISABLE_JEMALLOC: true
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=xxx
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/opt/immich-app/immich-data


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=xxx
#TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5leGFtcGxlLm5ldCIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N0IjogInR5cGVzZW5zZS0zLmV4YW1wbGUubmV0IiwgInBvcnQiOiAiNDQzIiwgInByb3RvY29sIjogImh0dHBzIiB9Cl0=

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

IMMICH_API_URL_EXTERNAL=<censored>


###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=

# LOG_LEVEL=verbose
#
DB_DATA_LOCATION=./postgres
```

### Reproduction steps

```bash
1.Update to v1.109.0
2.Run docker compose up -d
3.Check logs docker compose logs -f
```

### Relevant log output

```shell
immich_server            | /usr/src/app/node_modules/sharp/lib/sharp.js:114
immich_server            |   throw new Error(help.join('\n'));
immich_server            |   ^
immich_server            |
immich_server            | Error: Could not load the "sharp" module using the linux-arm64 runtime
immich_server            | ERR_DLOPEN_FAILED: libwebpdemux.so.2: cannot open shared object file: No such file or directory
immich_server            | Possible solutions:
immich_server            | - Ensure optional dependencies can be installed:
immich_server            |     npm install --include=optional sharp
immich_server            |     yarn add sharp --ignore-engines
immich_server            | - Ensure your package manager supports multi-platform installation:
immich_server            |     See https://sharp.pixelplumbing.com/install#cross-platform
immich_server            | - Add platform-specific dependencies:
immich_server            |     npm install --os=linux --cpu=arm64 sharp
immich_server            | - Consult the installation documentation:
immich_server            |     See https://sharp.pixelplumbing.com/install
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:114:9)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
immich_server            |     at Module.load (node:internal/modules/cjs/loader:1208:32)
immich_server            |     at Module._load (node:internal/modules/cjs/loader:1024:12)
immich_server            |     at Module.require (node:internal/modules/cjs/loader:1233:19)
immich_server            |     at require (node:internal/modules/helpers:179:18)
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
immich_server            |
immich_server            | Node.js v20.15.1
immich_server            | Detected CPU Cores: 4
immich_server            | /usr/src/app/node_modules/sharp/lib/sharp.js:114
immich_server            |   throw new Error(help.join('\n'));
immich_server            |   ^
immich_server            |
immich_server            | Error: Could not load the "sharp" module using the linux-arm64 runtime
immich_server            | ERR_DLOPEN_FAILED: libwebpdemux.so.2: cannot open shared object file: No such file or directory
immich_server            | Possible solutions:
immich_server            | - Ensure optional dependencies can be installed:
immich_server            |     npm install --include=optional sharp
immich_server            |     yarn add sharp --ignore-engines
immich_server            | - Ensure your package manager supports multi-platform installation:
immich_server            |     See https://sharp.pixelplumbing.com/install#cross-platform
immich_server            | - Add platform-specific dependencies:
immich_server            |     npm install --os=linux --cpu=arm64 sharp
immich_server            | - Consult the installation documentation:
immich_server            |     See https://sharp.pixelplumbing.com/install
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:114:9)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
immich_server            |     at Module.load (node:internal/modules/cjs/loader:1208:32)
immich_server            |     at Module._load (node:internal/modules/cjs/loader:1024:12)
immich_server            |     at Module.require (node:internal/modules/cjs/loader:1233:19)
immich_server            |     at require (node:internal/modules/helpers:179:18)
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
immich_server            |
immich_server            | Node.js v20.15.1
immich_server            | /usr/src/app/node_modules/sharp/lib/sharp.js:114
immich_server            |   throw new Error(help.join('\n'));
immich_server            |   ^
immich_server            |
immich_server            | Error: Could not load the "sharp" module using the linux-arm64 runtime
immich_server            | ERR_DLOPEN_FAILED: libwebpdemux.so.2: cannot open shared object file: No such file or directory
immich_server            | Possible solutions:
immich_server            | - Ensure optional dependencies can be installed:
immich_server            |     npm install --include=optional sharp
immich_server            |     yarn add sharp --ignore-engines
immich_server            | - Ensure your package manager supports multi-platform installation:
immich_server            |     See https://sharp.pixelplumbing.com/install#cross-platform
immich_server            | - Add platform-specific dependencies:
immich_server            |     npm install --os=linux --cpu=arm64 sharp
immich_server            | - Consult the installation documentation:
immich_server            |     See https://sharp.pixelplumbing.com/install
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:114:9)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
immich_server            |     at Module.load (node:internal/modules/cjs/loader:1208:32)
immich_server            |     at Module._load (node:internal/modules/cjs/loader:1024:12)
immich_server            |     at Module.require (node:internal/modules/cjs/loader:1233:19)
immich_server            |     at require (node:internal/modules/helpers:179:18)
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
immich_server            |
immich_server            | Node.js v20.15.1
immich_server exited with code 1
```

**Comment by thomasss02** [comment]
Same here

**Comment by nisby** [comment]
+1

**Comment by rubenixnagios** [comment]
same

**Comment by ryanrpj** [comment]
Same

**Comment by ChrislyBear-GH** [comment]
Same!

**Comment by No13** [comment]
Same in 1.109.1 unfortunately

**Comment by thomasss02** [comment]
Confirm same in 1.109.1

**Comment by tiomny** [comment]
Same in 1.109.1

**Comment by janriedler** [comment]
Same here in 1.109.1. Machine-Learning Container is working, Immich-Server Container is always restarting

**Comment by bo0tzz** [comment]
Fixed by #11194

**Comment by mstgrv** [comment]
I had this issue with v1.109.0, upgraded to v1.109.1 and it's still happening

**Comment by nisby** [comment]
same here with v1.109.1

**Comment by nisby** [comment]
fixed with v1.109.2
