### ISSUE TITLE
Not found or no album.update access (Immich Server Error)

### ISSUE THREAD

**Issue by szmarczak** [immich-app/immich#11295]
### The bug

![image](https://github.com/user-attachments/assets/b7663b6b-7083-4b5f-8e00-11674ac43e1e)

![image](https://github.com/user-attachments/assets/827beb1a-118d-43a5-9e27-22346533068b)

```
Not found or no album.read access - 400
Error: Error: 400
    at Object.de [as ok] (https://REDACTED/_app/immutable/chunks/fetch-client.DFOVVXby.js:1:2872)
    at async Promise.all (index 0)
    at async an (https://REDACTED/_app/immutable/nodes/6.CDMA6ikW.js:1:3174)
    at async Re (https://REDACTED/_app/immutable/chunks/entry.DxWK_9XB.js:1:13736)
```

### The OS that Immich Server is running on

Linux alpine 6.6.9-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 09:29:26 +0000 x86_64 Linux

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  cloudflared:
    restart: always
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token REDACTED

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=REDACTED
DB_DATABASE_NAME=REDACTED
```

### Reproduction steps

```bash
1. Open `Albums`
2. Click the `Create album` icon.
3. Type anything in the `Title` box.

Happens randomly.
```

**Comment by LiteApplication** [comment]
Can confirm, does not happen if you set the title of the album before adding anything to it.

**Comment by splattergamesextended** [comment]
I have the same problem. The web interface also glitches out. When you enter the title after adding photos first, the title box resets, the entered title disappears and the "add photos" button reappears again. 
What's even better, if you enter the title for the second time, it works and saves the album properly.

I have a slightly different stacktrace. 

Stacktrace
Error: Error: 400
    at Object.fe [as ok] (https://my.domain/_app/immutable/chunks/fetch-client.D4FW72yp.js:1:2872)
    at async Promise.all (index 0)
    at async vn (https://my.domain/_app/immutable/nodes/6.DsAVhoHO.js:1:3149)
    at async Re (https://my.domain/_app/immutable/chunks/entry.B21hFgyG.js:1:13736)

**Comment by alextran1502** [comment]
@splattergamesextended This issue should be fixed in `v1.131.1` just released today. Can you update and try again?

**Comment by splattergamesextended** [comment]
> @splattergamesextended This issue should be fixed in `v1.113.1` just released today. Can you update and try again?

that's the first thing I did actually, pulled the newest build just a few minutes ago. Problem still exists unfortunately. I also just tried to recreate the container, even tried from a private browsing window, exactly the same.

**Comment by RestartB** [comment]
Still facing this issue on `v1.115.0`. Issue doesn't happen if you set a title for the album before adding items.
```
Not found or no album.read access (400)
Stacktrace

le@http://(ip-address)/_app/immutable/chunks/fetch-client.CFZ4JfrO.js:1:2948
he@http://(ip-address)/_app/immutable/chunks/fetch-client.CFZ4JfrO.js:1:2872
```

**Comment by danieldietzler** [comment]
Can someone provide some exact steps to make it always fail?

**Comment by splattergamesextended** [comment]
> Can someone provide some exact steps to make it always fail?

Sure, it's always the same for me at least.

1. Go to sidebar -> Albums.
2. Create album
3. Add photos and select the photos you want.
4. Add title -> now when you type anything in here and press "enter" it bugs out and forgets the title (unless you retype it, then the bug does not happen). If it bugs out, the album is shown under "Albums" but doesn't exist actually, which you will notice when you click on it.

Hope that helps.

**Comment by danieldietzler** [comment]
Thanks @splattergamesextended that helped finding the bug :)

**Comment by Stats274** [comment]
This error is back in v1.141.1

**Comment by meesfrensel** [comment]
Cannot reproduce on latest with the reproduction steps given above. If the problem persists, please open a new issue with exact reproduction steps.
