### ISSUE TITLE
Selecting pictures in Safari doesn't trigger the upload

### ISSUE THREAD

**Issue by zionun** [immich-app/immich#12522]
### The bug

When using Safari (macOS and iOS), the "Select from computer" button inside an album correctly presents the file browser view, but after selecting one or more pictures and confirming, the file browser view closes and nothing happens in the album.
Opening the file browser again and selecting pictures for the second time usually works and selected pictures begin to be uploaded to the server.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.114.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. Open any album
2. Click on the "Add photos" icon
3. Click on "Select from computer"
4. Select one or more photos
5. Click Confirm. Nothing happens
6. Repeat from 2 -> Success

**Comment by danieldietzler** [comment]
Is this still broken? Did you make sure it actually didn't work and it wasn't a case of reloading for the assets to appear?

**Comment by zionun** [comment]
> Is this still broken? Did you make sure it actually didn't work and it wasn't a case of reloading for the assets to appear?

I just tried with the latest version (v1.131.2) and unfortunately it is still broken. I also noticed that the first click on "Select from computer" never shows the file browser; it must be clicked twice (not double click but two separate clicks) in order for the file browser to appear (both on iOS and macOS).

**Comment by JelloUp** [comment]
I have this same issue when trying to upload from Safari on iOS (when selecting from Photo Library or Take Photo). Nothing happens after selecting an image to add. Unfortunately, trying a second time still doesn't work.

**Comment by zionun** [comment]
Hello, I'm reopening this issue since it doesn't seem to be fixed in the new release (1.136.0).
What seems to be working now is the first click on the icon, which now opens immediately the menu while in the previous versions a second click was needed.
But after selecting the photo and tapping on the confirm button, no photo is uploaded. Opening the selection view and selecting the photo a second time triggers the upload.
Please see the screencast attached.

https://github.com/user-attachments/assets/b43a4e2d-be0d-4504-b0f4-16cba8e3efc1

**Comment by lbgracioso** [comment]
Hey, have you guys managed to do it on Safari? I'm actually having trouble with it on Firefox to iOS too.

**Comment by zionun** [comment]
Every time a new version is released, I hope that this bug is fixed. Unfortunately it is still there.
I have all my family using Immich now, and it's great in letting them browse the shared albums. The issues start when they want to upload pictures.
This bug with upload in Safari is really annoying and it is the main reason for my family not to share pictures. The steps are usually these:
- I tell them not to install the Immich iOS app because there's not a way to upload pictures directly from the photos app into an album (that's a shame: it should be a basic feature)
- I make them create a shortcut to the web app on the home of the iPhone, even if unfortunately the experience with the web app isn't great because the layout is broken and when browsing an album you can scroll both vertically and horizontally (there seems to be an extra space on the right of the grid)
- I then tell them to upload their pictures to the shared album; they start selecting all the pictures, tap on confirm and... nothing happens. After selecting dozens of pictures, they have to start again from scratch. At that point they say "ok then, I'll do it later" and of course it ends there.

I find it frustrating. There's not an easy way of using a shared album in Immich.
Please, address this issue or - even better - add the "upload from phone's library" button to the Immich app. It would make Immich the perfect app for sharing pictures with friends and family.
Thanks.

**Comment by brunobeeee** [comment]
Any updates on this? I love Immich, but this prevents me from using shared albums.

From OP's initial description:
> 1. Open any album
> 2. Click on the "Add photos" icon
> 3. Click on "Select from computer"
> 4. Select one or more photos
> 5. Click Confirm. Nothing happens
> 6. Repeat from 2 -> Success

Repeating from 2 does not fix the issue for me. It's just hit or miss (like 1/10 chance).

Nonetheless, thank you for this fantastic piece of software!

**Comment by Vojtik69** [comment]
Confirming this issue. I can't reproduce it personally (I am team Android :-) ), but my friend report it when I shared a link with her.

**Comment by mrxder** [comment]
Same issue here with Immich v3.0.1. It happens specifically when the selected photos aren't stored locally and need to sync from iCloud first. There's a noticeable delay before the picker closes, and after that, the upload just never starts, no error, no reaction. Photos already on-device upload fine most of the time. Suspect the iCloud delay causes the file input's change event to get dropped in Safari/WebKit.
Setup: iPhone, Safari, shared album link with upload enabled, Immich v3.0.1.

**Comment by TimGoll** [comment]
The linked pull request lets me assume that this was fixed for v3.1.0? I have that version on my server and the issue still exists. So I guess it wasn't fixed after all?

**Comment by crisan7** [comment]
> The linked pull request lets me assume that this was fixed for v3.1.0? I have that version on my server and the issue still exists. So I guess it wasn't fixed after all?

for me it works now in version 3.1.0
