### ISSUE TITLE
multiple tag per asset + hiearchical tags => one big tag in immich

### ISSUE THREAD

**Issue by aisbergde** [immich-app/immich#12542]
### The bug

tags are not detected as required.
example:

`Location|Deutschland,Location|Deutschland|Berlin|Kladow|Verlängerte Uferpromenade,Location|Deutschland|Berlin|Kladow,Location|Deutschland|Berlin`

this is detected by immich as one tag. But it should be multiple hierarchical tags.
these multiple tags are delimited by ","
![image](https://github.com/user-attachments/assets/d39f1056-d3fb-46f9-8c85-b1b85dc921a3)

### The OS that Immich Server is running on

docker in synology containers

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.114.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1.
2.
3.
...

**Comment by Mraedis** [comment]
Are these in `Keywords` or in `HierarchicalSubject` ?

**Comment by bo0tzz** [comment]
Should be fixed by #12509

**Comment by aisbergde** [comment]
still not fixed
![Screenshot_2024-12-06-04-36-47-996_com.android.chrome.jpg](https://github.com/user-attachments/assets/d1041dfe-475c-4abd-bf73-8afbc2149635)

**Comment by aisbergde** [comment]
I mean, it is fixed that it's not a big tag now, but it's not hierarchical. Or how to configure to see a hierarchy?
