### ISSUE TITLE
Scroll bar on the timeline does not show the year of the oldest photo

### ISSUE THREAD

**Issue by radh21301** [immich-app/immich#12598]
### The bug

If this is a feature request rather than a bug, please do convert it. I wasn't sure where to add this.

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/dc92cff9-f297-43ab-a757-b90a8bfc692d">

The oldest photos I have are from 2004, but the scrollbar only shows 2013. Yes, 2013 is when I have a lot of images, but it is confusing this way. It would be ideal to at least show the year of the oldest photo in the timeline.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.114.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
na
```

### Your .env content

```Shell
na
```

### Reproduction steps

Login to the account on a browser and observer the years shown on the right

**Comment by SoPat712** [comment]
I'm experiencing the exact same bug, I have photos from 1998, but my timeline only goes from 2024 to 2004.

I'm running it in Docker on v1.124.2.

**Comment by danieldietzler** [comment]
Hey, this should be fixed with the recent timeline refactoring. Could you verify?

**Comment by radh21301** [comment]
Hey. I am on the latest version (v1.131.3) and the issue still exists.

**Comment by wuzihao051119** [comment]
This is expected behavior. The distance between the year label is so close and it is less then `MIN_YEAR_LABEL_DISTANCE=16` px.
So the year label will not display.
It's not related to oldest photos. As long as the distance is so close, the year label will disappear.
See [here](https://github.com/immich-app/immich/blob/main/web/src/lib/components/shared-components/scrubber/scrubber.svelte#L156).

**Comment by radh21301** [comment]
I am not sure of the technical details.

But I guess from an end user perspective, it is very confusing to not see the oldest year in the timeline. Maybe this 'dropping' the year should not be applicable to the latest and oldest years?

**Comment by jrasm91** [comment]
This isn't a bug, but more of a feature request. Feel free to open a request for it in [Github Discussions](https://github.com/immich-app/immich/discussions/categories/feature-request).
