### ISSUE TITLE
[BUG] Shared Albums photo sorting and missing exif information

### ISSUE THREAD

**Issue by msbt** [immich-app/immich#1292]
First of all, thanks for the new public sharing feature, that's exactly what I was waiting for and eager to check out!

**Describe the bug**
I created an album where all the images are in the correct order (which is the date), but when creating a share-link and accessing that, the images are in random order and there is no exif info available (I reckon that's the reason for the lack of sorting, that's why I included both issues in this one).

When I access the shared image directly (i.e. `/shareid/photos/photoid`) the exif information is showing, but when I go back to the overview and open the image again, it's gone.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Create Album
2. Upload Photos
3. Create Share Link (I only tried with no upload and no expiration date)
4. Access Link and wonder why the sorting is different and the exif info isn't avilable

**Expected behavior**
Have the same sorting as the unshared album

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8767096/211667692-94043f49-ebab-4d0b-84c0-27a376bc50c6.png)

**System**
- Server Version: `v1.41.0`

**Comment by alextran1502** [comment]
It is fixed and merged in https://github.com/immich-app/immich/pull/1283 for the EXIF issue. I will take a look at the order issue

**Comment by msbt** [comment]
haha what, you're just too fast! I just added another note in case you missed that, which might help to debug:
"When I access the shared image directly (i.e. `/shareid/photos/photoid`) the exif information is showing, but when I go back to the overview and open the image again, it's gone."
