### ISSUE TITLE
Keep Android version as up-to-date on F-Droid as it is on the Play Store

### ISSUE THREAD

**Issue by emes81** [immich-app/immich#12954]
### The bug

As of today, 26 September 2024, the F-Droid app is on 1.112.1 (last updated 18 August), while the Google Play version is on 1.115.0 (last updated 12 September).
Keeping the F-Droid version as up-to-date as the Play Store version would allay user anxieties about the app suite's commitment to open-source values and communities.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

1.114.0

### Version of Immich Mobile App

 1.112.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

N/A

**Comment by alextran1502** [comment]
Fdroid release is fixed and should be updating again with the latest release `v1.116.0`

**Comment by MisterrrX** [comment]
> Fdroid release is fixed and should be updating again with the latest release `v1.116.0`

F-Droid release is still stuck on 1.112.1

**Comment by dabluecaboose** [comment]
This is closed, but it's still an issue.  I just set up a server for the first time and spent a good 30 minutes trying to figure out why the app wouldn't connect.  None of your documentation or logging suggests that a version mismatch was the culprit, but I figured it out by trial and error and by finally downloading the latest APK directly from the github.

**Comment by MisterrrX** [comment]
I think this is partly an F-Droid issue. As far as I know they manually review every update, which takes some time.  To be fair, it usually doesn't take _that_ long. I just got 1.118.1 today, which was released 6 days ago. I recall it taking usually 2 or 3 days.

As long at it's getting updated I don't really care, I just pin my server version and wait until the F-Droid release is out.
