### ISSUE TITLE
Slideshow ignores video length

### ISSUE THREAD

**Issue by jvgoch** [immich-app/immich#13874]
### The bug

Previously if a video would come along in a slideshow it would play for it's entire length and go to the next photo or video regardless of what the slide duration was set to.
Now the slideshow either skips the rest of the video if the video is longer than the slideshow duration or it stays frozen on the last frame if the video is shorter than the slideshow duration.

### The OS that Immich Server is running on

Ubuntu 22.04.1 LTS

### Version of Immich Server

v1.119.1

### Version of Immich Mobile App

Still no slideshow on the app :'(

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
      
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
#      - pgdata:/var/lib/postgresql/data
#      - /immich/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:

  model-cache:
#  pgdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=
DB_DATA_LOCATION=
TZ=
IMMICH_VERSION=release
DB_PASSWORD=
DB_USERNAME=
DB_DATABASE_NAME=
```

### Reproduction steps

1. Start slideshow with duration 10
2. Play video that's longer or shorter than 10 seconds 
3. Watch the frame freeze for the remaining time if it's shorter or skip the rest of the video if it's longer

### Additional information

Some helpful info from a discord user
![image](https://github.com/user-attachments/assets/0a98dede-268d-4c3b-aee5-984806e24cdc)

**Comment by jvgoch** [comment]
Not an issue anymore.
Probably fixed by https://github.com/immich-app/immich/pull/13883

**Comment by jocxfin** [comment]
This issue is back again with the latest [v1.135.3](https://github.com/immich-app/immich/releases/tag/v1.135.3) release.
