### ISSUE TITLE
Error when saving remote Live Photo on iOS app

### ISSUE THREAD

**Issue by JacobBumgarner** [immich-app/immich#15805]
### The bug

This seems specific to a few different images in my data base. I've zipped one of them as an example.

I notice that when the download popups show, rather than it showing a `.jpeg` and `.mov` file, it's downloading two `.jpeg` files:

<img src="https://github.com/user-attachments/assets/e0edf282-f6f2-49ec-b3f9-f1582774a558" width=200px/>

See below for the output when a Live Photo in `.heic` format is successfully downloaded:

<img src="https://github.com/user-attachments/assets/be960c25-1996-468a-84a6-e22994cf23dd" width=200px/>

---
FWIW, I know that this was a photo that my wife sent me from her iPhone at the time that I then saved to my own iOS camera roll. This was ~3 years ago, so I was not using Immich at the time. 

Lastly, this and the other live photos with Download issues can be viewed in the web/iOS apps, and I confirmed that the live photo video *is* successfully linked by examining the assets via the Immich API.

Happy to provide any other information that may be useful to get this one figured out.

---

I've attached a screenshot of the error log below:
<img src="https://github.com/user-attachments/assets/528eedc8-8299-4cab-9221-1d8e4a0c2c55" width=200px/>

### The OS that Immich Server is running on

Ubuntu 24.04.1

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.3 build.191

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: "no"
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: "no"
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: "no"

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: "no"

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/vault/photo_library/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=EST

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD={BLANK}

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Click the cloud "Download" button on the Immich iOS app.
2. Fail to download the image.

### Relevant log output

```shell
See main text for error lo screenshot.
```

**Comment by pandyajay1997** [comment]
Any idea when this will be fixed? Currently having this issue where my Iphone is not able to redownload the live photo via immich IOS app.

**Comment by Kieranwest** [comment]
I seem to be getting the same behaviour

**Comment by Ephaltes** [comment]
Shouldn’t this get a high priority? In my opinion not being able to download a photo in a photo backups app sounds like a major problem

**Comment by YuanBLQ** [comment]
The same issue occurred.
- App version: 2.0.1 build.230
- Server version: 2.0.1

<img width="300" height="460" alt="Image" src="https://github.com/user-attachments/assets/9359d7f9-f27c-4a4b-8589-2331efe8a3cd" />

**Comment by YuanBLQ** [comment]
> The same issue occurred.
> 
> * App version: 2.0.1 build.230
> * Server version: 2.0.1
> 
> <img alt="Image" width="300" height="460" src="https://private-user-images.githubusercontent.com/18660424/500526000-9359d7f9-f27c-4a4b-8589-2331efe8a3cd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA3OTA4MzgsIm5iZiI6MTc2MDc5MDUzOCwicGF0aCI6Ii8xODY2MDQyNC81MDA1MjYwMDAtOTM1OWQ3ZjktZjI3Yy00YTRiLTg1ODktMjMzMWVmZThhM2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDE4VDEyMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMzhkMmVkYjc4OWRlNTFiZGYyODhkZWIwYmJhMDY0Mzg5NjcyOTk1M2Q4NzdjYjc2N2E5ZjAyMmUwZGQ3MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3kw8j4TYswU8ifIeiq_4WAm6BqVH2AxxmmFSZiHe6Vc">

Looks like it's fixed in v2.1.0.

**Comment by JacobBumgarner** [comment]
It's still not working for me with the original image I posted. I'm on v2.1.0

<img width="200" alt="Image" src="https://github.com/user-attachments/assets/e3f499d4-5d20-4cad-987a-9e48d61eecb9" />

**Comment by YuanBLQ** [comment]
> It's still not working for me with the original image I posted. I'm on v2.1.0
> 
> <img alt="Image" width="200" src="https://private-user-images.githubusercontent.com/70919881/503067396-e3f499d4-5d20-4cad-987a-9e48d61eecb9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExMjU1MDcsIm5iZiI6MTc2MTEyNTIwNywicGF0aCI6Ii83MDkxOTg4MS81MDMwNjczOTYtZTNmNDk5ZDQtNWQyMC00Y2FkLTk4N2EtOWU0OGQ2MWVlY2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIyVDA5MjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2IyNzJhMDc5MDZiYzI2NjAzMmY2ZWMwNzZhYzk5NGI5ODRmYmIwMWU2ZTljOTI0MTNiOGY5ZTc1ZWNiOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q-I99C9tuy7hBEYO4gqkD78p7vJZ2a3D1exPMU50L-I">

Have both the `App` and `Server` been upgraded?

**Comment by JacobBumgarner** [comment]
> > It's still not working for me with the original image I posted. I'm on v2.1.0
> > 
> > <img alt="Image" width="200" src="https://private-user-images.githubusercontent.com/70919881/503067396-e3f499d4-5d20-4cad-987a-9e48d61eecb9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExMjU1MDcsIm5iZiI6MTc2MTEyNTIwNywicGF0aCI6Ii83MDkxOTg4MS81MDMwNjczOTYtZTNmNDk5ZDQtNWQyMC00Y2FkLTk4N2EtOWU0OGQ2MWVlY2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIyVDA5MjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2IyNzJhMDc5MDZiYzI2NjAzMmY2ZWMwNzZhYzk5NGI5ODRmYmIwMWU2ZTljOTI0MTNiOGY5ZTc1ZWNiOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q-I99C9tuy7hBEYO4gqkD78p7vJZ2a3D1exPMU50L-I">
> 
> Have both the `App` and `Server` been upgraded?

Yes

**Comment by GHA193** [comment]
I have the same issue.
iOS version: iOS 26.1
App version: 2.2.3.build.235
Server version: 2.2.3

**Comment by dreamrukia** [comment]
@bo0tzz We should reopen this issue. I'm on v2.3.1 and the issue still exist. I have uploaded a live photo from android device and downloading on iOS app fails. This issue was fixes in previous version but happens again.

**Comment by ngoc-minh-do** [comment]
@bo0tzz I confirmed this issue happened again

**Comment by radk0n9** [comment]
Hello, any update here? I'm facing the same issue.
Server Version: v2.7.5
App Version: 2.7.5 build.256
iOS Version: 26.5.1
