### ISSUE TITLE
Photo description bugs

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#15990]
### The bug

1) Newly entered description stays there (only visually) while listing photos by left-right buttons until photo with another non-empty description comes. Additonally when that stucked description is entered on asset without a description, it's saved to it as well on exit
2) Panorama photos description imported from asset (attached) cannot be deleted, when it's deleted and saved as empty it appears again after asset is reloaded

https://github.com/user-attachments/assets/4ac29a34-cf9c-4dbc-9e97-4bfe9a719354

![Image](https://github.com/user-attachments/assets/d2d6cfc2-52b9-4f17-aca8-c709ff7cf28b)

### The OS that Immich Server is running on

Fedora 41

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

above and attachements

### Relevant log output

```shell

```

**Comment by orrd** [comment]
These are still problems in the current 1.134.0 release. 

The 2nd problem if not being able to set a description to blank happens with any photos with an existing exif description (not just panoramas).  I actually just created a separate issue for that problem earlier today at #19168 before I saw the mention of the same problem in this issue.   But I'll leave it open since they may want to have a separate issue for that problem and the left-right photos problem, since they're probably two separate bugs.

**Comment by alextran1502** [comment]
should be fixed

**Comment by waclaw66** [comment]
> should be fixed

No, still an issue.

**Comment by orrd** [comment]
Yeah, it's definitely still an issue with the current 2.5.5 release.

**Comment by waclaw66** [comment]
Nope, still there.
Repro steps:
1. Type desc to an asset.
2. Click to left or right arrow by mouse.
3. Click arrow to get back. Desc is present.
4. Delete desc.
5. Click to left or right arrow by mouse.
6. Click arrow to get back.
7. Desc still there, shouldn't be.
8. F5, desc is gone.

**Comment by danieldietzler** [comment]
The PR was merged two hours ago, lol. There hasn't been any release whatsoever

**Comment by waclaw66** [comment]
> The PR was merged two hours ago, lol. There hasn't been any release whatsoever

Main branch tested.

**Comment by danieldietzler** [comment]
#26257 should've definitely fixed it though

**Comment by waclaw66** [comment]
> [#26257](https://github.com/immich-app/immich/pull/26257) should've definitely fixed it though

Yes, this one does.
