### ISSUE TITLE
iOS Live Photos Sometimes Only Uploads Video, Photo Won't Auto Backup

### ISSUE THREAD

**Issue by cole21771** [immich-app/immich#16670]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I've realized that at least a handful of times over the last few months that some of my live photos are only uploading the video part of them and not the photo part. I can see the photo says it isn't backed up in immich, clicking upload works perfectly and backs up the photo, but for some reason, the photo won't auto backup like everything else. 

See two examples from last week:
![Image](https://github.com/user-attachments/assets/cfa64ca9-d26e-41ca-bd1d-45d5fda862fd)
![Image](https://github.com/user-attachments/assets/1ec320b6-589d-487e-b3fc-87e469f498de)

I have plenty of other live photos that have no issues backing up, not sure why only a few don't auto backup. Clicking manual "start backup" doesn't find them either. I have the recents album synced among a few other manual ones, so they should show up from there like everything else.

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

1.128.0 build.196

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
I have no idea how to get this from TrueNAS
```

### Your .env content

```Shell
I have no idea how to get this from TrueNAS
```

### Reproduction steps

I have no idea how to reproduce it, please let me know if there are some logs from the app you'd like me to get

### Relevant log output

```shell

```

**Comment by mmomjian** [comment]
I'm also experiencing this. Unable to identify exactly why. Long-pressing on the asset and clicking "upload" does force them to get linked in the web UI.

**Comment by YarosMallorca** [comment]
For me, this started happening around 1.127.0, maybe a bit earlier.

**Comment by Glimmer868** [comment]
Came here to hunt for exactly this bug. I am experiencing too although in my case it seems to upload the movie part and the image part separately and shows it twice in Immich.

**Comment by ThowZzy** [comment]
Still a big issue to this day on IOS. Reinstalling the app used to reliably re-upload them all, but I experienced a hit and miss experience trying this way. Only a manual upload of all not-uploaded files work in some cases.

A temporary solution to help us with this issue could be to add a filter function on IOS to show ALL not uploaded files. This way we could select in bulk all files that are not uploaded to the server and upload them. 
Or something like this, even a new button in the settings to manually scan for not-uploaded files and force upload them ?

For the record, I started noticing this issue around the 21th of january 2025. Could have started happening at least a couple months earlier than this.

**Comment by f3ndot** [comment]
@ThowZzy you, and others, can upvote for that filter feature here: https://github.com/immich-app/immich/discussions/2155

**Comment by jrasm91** [comment]
This should be fixed in the new timeline!

**Comment by hobyvh** [comment]
I'm experiencing this as well, now, with version 2.7.4 server and 2.7.5 build.256 iOS. So I don't think it's fixed.

I'm just starting to try immich and after fully backing up successfully at home from two phones, both with Enable Backup set to On have uploaded videos-only of live photos when on cellular, out and about.
