### ISSUE TITLE
[API] tagAssets doesn't tag all assets randomly

### ISSUE THREAD

**Issue by simulot** [immich-app/immich#16747]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

The API call tagAssets often tags not all assets given in the call.

 

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

I writing test cases for Immich-go, that wipes out the immich's tables, and upload a handful of images, with tag and album. 

May be 1 over 3 test3, immich misses to tag an asset.
The API call return show a success for all tagged assets

### Relevant log output

```shell
immich_server  | [95m[Nest] 17  - [39m03/09/2025, 1:17:28 PM [95m  DEBUG[39m [33m[Api:LoggingInterceptor~9bcb8x7p][39m [95mPUT /api/tags/bececdd5-bb46-4201-8551-a0300809c12c/assets 200 27.63ms ::ffff:172.18.0.1[39m
immich_server  | [96m[Nest] 17  - [39m03/09/2025, 1:17:28 PM [96mVERBOSE[39m [33m[Api:LoggingInterceptor~9bcb8x7p][39m [96m{"ids":["44891c00-8964-4882-a921-70c781d4a89a","bdfe3e04-9c24-4ada-8bac-69952f38a283","19182cda-f568-4c74-ade4-7b3a53a2a602","c9f9e3ce-3054-480b-85eb-f718e21401ea","807af51b-e29f-4db0-951c-904c57e8441d"]}[39m
```

### Additional information

Immich-go api trace:
```
025-03-09T14:17:28+01:00 QUERY 13 UpsertTags PUT http://localhost:2283/api/tags
   Content-Type [application/json]
   Accept [application/json]
   X-Api-Key redacted
-- body start --
{"tags":["tag/subtag"]}
-- body end --

2025-03-09T14:17:28+01:00 RESPONSE 13 UpsertTags PUT http://localhost:2283/api/tags
  Header:
     Date : Sun, 09 Mar 2025 13:17:28 GMT
     Connection : keep-alive
     Keep-Alive : timeout=5
     X-Powered-By : Express
     X-Immich-Cid : rtoee2rp
     Content-Type : application/json; charset=utf-8
     Content-Length : 212
     Etag : "d4-WX1a0e5OR3gUbCjRKZNhnbYtz24"
  Status: 200 OK
-- response body start --
[{"id":"bececdd5-bb46-4201-8551-a0300809c12c","parentId":"a4af078e-4993-4aef-b774-49dd3ee08cc2","name":"subtag","value":"tag/subtag","createdAt":"2025-03-09T13:17:28.192Z","updatedAt":"2025-03-09T13:17:28.192Z"}]
-- response body end --

2025-03-09T14:17:28+01:00 QUERY 14 TagAssets PUT http://localhost:2283/api/tags/bececdd5-bb46-4201-8551-a0300809c12c/assets
   X-Api-Key redacted
   Content-Type [application/json]
   Accept [application/json]
-- body start --
{"ids":["44891c00-8964-4882-a921-70c781d4a89a","bdfe3e04-9c24-4ada-8bac-69952f38a283","19182cda-f568-4c74-ade4-7b3a53a2a602","c9f9e3ce-3054-480b-85eb-f718e21401ea","807af51b-e29f-4db0-951c-904c57e8441d"]}
-- body end --

2025-03-09T14:17:28+01:00 RESPONSE 14 TagAssets PUT http://localhost:2283/api/tags/bececdd5-bb46-4201-8551-a0300809c12c/assets
  Header:
     Keep-Alive : timeout=5
     X-Powered-By : Express
     X-Immich-Cid : 9bcb8x7p
     Content-Type : application/json; charset=utf-8
     Content-Length : 306
     Etag : "132-Nm/wGpjeBvL9J1m/yBxBNA+kiHY"
     Date : Sun, 09 Mar 2025 13:17:28 GMT
     Connection : keep-alive
  Status: 200 OK
-- response body start --
[{"id":"44891c00-8964-4882-a921-70c781d4a89a","success":true},{"id":"bdfe3e04-9c24-4ada-8bac-69952f38a283","success":true},{"id":"19182cda-f568-4c74-ade4-7b3a53a2a602","success":true},{"id":"c9f9e3ce-3054-480b-85eb-f718e21401ea","success":true},{"id":"807af51b-e29f-4db0-951c-904c57e8441d","success":true}]
-- response body end --
```

The table tag_asset content:
```
"assetsId"	"tagsId"
"807af51b-e29f-4db0-951c-904c57e8441d"	"bececdd5-bb46-4201-8551-a0300809c12c"
"44891c00-8964-4882-a921-70c781d4a89a"	"bececdd5-bb46-4201-8551-a0300809c12c"
"bdfe3e04-9c24-4ada-8bac-69952f38a283"	"bececdd5-bb46-4201-8551-a0300809c12c"
"c9f9e3ce-3054-480b-85eb-f718e21401ea"	"bececdd5-bb46-4201-8551-a0300809c12c"
```

full logs attached

[log.log](https://github.com/user-attachments/files/19149904/log.log)

[immich-go_2025-03-09_14-17-27.trace.log](https://github.com/user-attachments/files/19149909/immich-go_2025-03-09_14-17-27.trace.log)

**Comment by danieldietzler** [comment]
To clarify; this is a race condition between metadata extraction updating tags. Uploading multiple images and *immediately* updating the tags will cause this.

**Comment by Chaoscontrol** [comment]
> To clarify; this is a race condition between metadata extraction and updating tags. Uploading multiple images and _immediately_ updating the tags will cause this.

I've tried using immich-go (in separate tests):

- Delaying all tagging to the end of the process, instead of tagging right after each upload
- Adding a 30s delay after all uploads have completed, to avoid tagging _immediately_
- Allowing all the uploads, then resuming the "Extract Metadata" job, wait for 1 minute to allow the job to easily complete, and then run tagging

None of this worked or made any difference. Not sure what else I can try. In some occasions, 1 asset was tagged. Other times it was a bunch (8-10). Never more than that. The assets tagged had all their expected tags, so it's an all or nothing case. 

I honestly don't understand the issue enough, but I fail to comprehend (if the issue is updating right after upload) why the album "update" works even when done right after. This doesn't cause any issue, and all photos are always assigned to the expected album. 

But tag updates seem to work differently, so it's not "any" update. 

Sad to see the PRs that were meant to fix this issue died halfway. :(

**Comment by Chaoscontrol** [comment]
### For those facing this issue and looking for a temporary workaround via immich-go.

I have built a patched version with a new option to skip tagging and improve logs to allow for manual tagging via easy API calls. You can find more info a download it [here](https://github.com/Chaoscontrol/immich-go/releases/tag/v27.1-patch).

Disclaimer: I am no dev. I have no clue of what I'm doing. This was done mostly using AI. This is the first time ever I create a release in Github, and even my own repo. The code might not be perfect. BUT it works.

**Comment by Chaoscontrol** [comment]
@danieldietzler Is it possible this issue is not only specific to tags?

Doing a few test updates repeatedly and I'm finding the same kind of behaviour for ALL metadata. The result is that photos upload fine, but a few seconds right after, when refreshing the server page, some photos metadata has been wiped. It's easily seen because some photos suddenly move position in the timeline and show up with today's date instead.

It's inconsistent, sometimes they all keep the data (in my test upload of 4 photos), sometimes a few are retained and a few wiped. It's quite random, which made me instantly think back to this issue with the tags.

And really, since I "think" both cases work updating the asset (even if using different API calls) right after upload... this seems strongly related...

Very surprised no-one has reported this before. Metadata is way more used than tags, and people even more fussy about it being lost.

**Comment by danieldietzler** [comment]
> Is it possible this issue is not only specific to tags?

Absolutely! It affects all metadata updates.

**Comment by binarybumpkin** [comment]
Hi, I think this issue needs to be re-opened.

Using the latest releases of immich (v2.4.1) and immich-go (v0.31.0) I can confirm that immich is still randomly not saving tags to all assets uploaded and tagged, despite the immich-go logs and API trace logs confirming tags are applied to assets - the immich UI shows random application of tags to assets once uploading has been completed.

I have tried this today on a fresh installation to reproduce it and report back, having confirmed this issue commit is indeed in v2.4.1 (actually included as part of v2.4.0 release).

Reproduction steps:
1. Set up a new docker environment (docker-compose.yml included below)
2. Edit the `.env` file to ensure `IMMICH_VERSION=v2.4.1`
3. Start immich app environment with `docker compose up -d --build` (Build is optional, but in case you've made changes)
4. Log into immich UI and create admin account
5. In Admin user preferences, go to Features and enable Tags & Tags in the sidebar
6. In Admin user preferences, create an API key (just enable ALL permissions)
7. Download the latest release of immich-go (v0.31.0)
8. Create a folder `Admin/Albums/Receipts` and put a bunch of images in there.
9. Run the `upload_batch.sh` script (see below).

EXPECTED RESULT:
- All 15 images should have 2 tags each in the Immich UI.

RESULT: 
- immich-go log outputs show jobs being paused, tags being created, assets being tagged (two tags applied correctly per image) e.g 15 images creates 30 tags
- immich-go API trace log outputs also show images being uploaded correctly, tags being created, tag 1 of 2 being applied to 15 assets, tag 2 of 2 being applied to 15 assets, all success/true, etc.
- In the immich UI, looking in the album and clicking through each image asset, some images have both tags, some have only one tag, some images have no tags at all. 
- This appears to be totally random, because if you snapshot the database and library folders after creating the API key (and `docker compose stop`) and repeat the scripted upload of the images after resetting the snapshot, docker volumes, etc. then different assets are tagged differently.

As shown in the script, I've also tried reducing the concurrency in case the immich-go requests are stepping on each other or out of order, etc.

So, ~~there doesn't seem to be any workaround, and~~ **are** a few potential related issues around, such as https://github.com/immich-app/immich/issues/23861 (which might be a duplicate) or https://github.com/simulot/immich-go/issues/990 (which also references this issue, **and mentions a few potential workarounds, one which works - see below**). 

What I'm seeing above/below points to something else in immich not saving the tags when they're set via the API?

Files pasted below for reproduction and testing, as well as logs.

# Confirmed Workaround: Tag via Sidecar Feature 

The commit/workaround by @niieani mentioned in https://github.com/simulot/immich-go/issues/990 here is yet to be reviewed and merged into @simulot's official repo, but I've confirmed it works:
- https://github.com/simulot/immich-go/issues/990#issuecomment-3398141713

All tags are applied to newly uploaded image assets (and presumably existing/updated ones, I've not tested that yet), and I even added additional tags with `--tag="tag3" --tag="tag4"` and all 15 image assets had all 4 tags applied in the Immich UI immediately after uploading.

The immich-go installation instructions to build it are fairly easy, but I wanted a statically linked binary, and didn't want to install any dependencies on the host, so I built it inside a native `golang` docker container using niieani's fork of @simulot's immich-go repo and used the `CGI_ENABLED=0` env variable, like so:

```
# docker run -v /tmp/immich-go-build:/host/immich-go-build -ti golang /bin/bash
# cd /host/immich-go-build
# git clone https://github.com/niieani/immich-go.git niieani-immich-go
# cd niieani-immich-go
# git checkout c13981a35066422a6ecb812edfd2c01d0c7eab81
# CGO_ENABLED=0 go build
```
This binds the /tmp/immich-go-build folder on the host inside the `golang` build container and starts it with an interactive shell, clones niieani's repo into the container (and host folder), checks out the commit for the `feat/tag-via-sidecar` branch, and compiles the `immich-go` binary as a statically linked executable, which you'll find on the host at `/tmp/immich-go-build/niieani-immich-go/immich-go`.

Then you can exit/terminate/cleanup the container, and the binary is available for use on the host with the `--tag-via-sidecar` CLI argument.

I haven't reviewed the code in detail (e.g. for security, etc.) but hoping @simulot or other devs can review the PR and add this feature into immich-go while the immich bug in this issue is resolved (properly? again?).

Attachments:
==
[docker-compose.yml](https://github.com/user-attachments/files/24718498/docker-compose.yml)
[upload_batch.sh](https://github.com/user-attachments/files/24718497/upload_batch.sh)
[upload_batch.log](https://github.com/user-attachments/files/24780469/upload_batch.log)
[upload_batch.trace.log](https://github.com/user-attachments/files/24718499/upload_batch.trace.log)
[env.txt](https://github.com/user-attachments/files/24718605/env.txt)

**Comment by danieldietzler** [comment]
Sorry @binarybumpkin, fixed in #25435

**Comment by binarybumpkin** [comment]
No problem @danieldietzler, thanks for the quick response! Hopefully that's the last change, and it will be satisfying to see this long running issue resolved! 👍

**Comment by avaly** [comment]
I'm still experiencing the issue described in this thread when I tag assets right after I upload them via the API. I'm using v2.6.1.
