### ISSUE TITLE
iOS/iPadOS Client Issues: Video Distorted, EXIF Wrong

### ISSUE THREAD

**Issue by novate** [immich-app/immich#17374]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

There are some iOS/iPadOS Client Issues:
- Video is distorted, horizontal became vertical, and vice versa. Image is fine. Starting from at least 1.130.x or around two weeks ago.
  - Not all videos have this issue.
- EXIF is matched wrong to photos/videos, starting from at least 1.131.3.
  - The timeline is fine.

All above mentioned issues does not exist in Web client.
iOS/iPadOS are all 18.4.

### The OS that Immich Server is running on

Fedora 41.20250330.1

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3.build.201

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - <redacted>:/mnt/media/cloud
    env_file:
      - .env
    ports:
      - <redacted>
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - immich-db:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
  immich-db:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=<redacted>

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=<redacted>

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=<redacted>
DB_DATABASE_NAME=<redacted>
```

### Reproduction steps

1. Open iOS/iPadOS Immich app.
2. Open a video, some of the videos can be distorted.

![Image](https://github.com/user-attachments/assets/ebcf3711-6b98-4634-be2f-e0fbf68697cc)

3. Open any image/video, and swipe up, the EXIF data is wrong.

Checked Web client for the same features and it worked normally.

### Relevant log output

```shell

```

**Comment by alextran1502** [comment]
Can you please metadata extraction for all and then logout and log back in?

**Comment by novate** [comment]
> Can you please metadata extraction for all and then logout and log back in?

@alextran1502 Thanks for the reply, will try it out. Meanwhile what I don't understand is that the web client works fine so I suppose it should supposed to be a client-side issue?

**Comment by novate** [comment]
Confirm that after ran extract metadata for all, log out and log back in the iOS app, the issue persists.

**Comment by alextran1502** [comment]
Can you help zip up the file and share it here? Thank you

**Comment by shenlong-tanwen** [comment]
@novate Looks like the EXIF data is all messed up. How was this asset uploaded to Immich and can you confirm if the EXIF data displayed in the web app matches the one from the iPhone Gallery?

Can you also go to Settings -> Advanced and enable the Troubleshooting setting, go back to the same asset, swipe up and share a screenshot of the metadata displayed?

**Comment by televoicepl** [comment]
I can confirm. Via web it's ok, but in the app it shows Exit (date, time, map) from another random photo from gallery. 
Advanced view in app shows correctly data. I noticed that it probably only applies to recently uploaded resources.
It fixes after refreshing the metadata for a specific photo via the web. But logging out and logging in again causes the same problem again.

**Comment by s4n-cz** [comment]
This is not only issue on iOS/iPad, but on the Android as well.

When I check the video on Android, it has wrong metadata. On web, the same video has correct metadata and works fine.

Server Version: 1.131.3
App Version: 1.130.3 build.191 (from Google Play Store)

![Image](https://github.com/user-attachments/assets/9269cf58-5b6d-4a3f-8190-8b451495ddeb)

**Comment by iMarKoLiGa** [comment]
Same issue for me only with iOS app. With the Web Client everything seems ok.

**Comment by alextran1502** [comment]
Hello, for those with incorrect metadata issue, can you provide a way to reproduce it?

**Comment by shenlong-tanwen** [comment]
I cannot reproduce this issue, but I found an issue with the exif update logic while going through the logic which could be related to this issue - #17407

**Comment by PirvuCatalin** [comment]
Also happens to me on the ios app (web view is fine) - what I did was to upgrade to v1.131.3, then import new images/videos from external library.

**Comment by novate** [comment]
@alextran1502 @shenlong-tanwen Sharing more context about my findings:

- The images are not from a regular upload, but external folders.
- An "extract metadata for all" job doesn't help.
- All newly added files works fine. Old files before v1.131 were bad in iOS. Web is always fine.
- A "clean rebuild" helps: I deleted immich folders and docker volumes, rebuild immich on the same external folders. After all jobs ran, iOS comes back to normal.

Points 3 and 4 can explain why people can't repro the issue.

**Comment by s4n-cz** [comment]
> * The images are not from a regular upload, but external folders.

I am not using external folders and the issue still occurred. But in my case I have uploaded lots of files through the [Immich CLI](https://immich.app/docs/features/command-line-interface/).

**Comment by iMarKoLiGa** [comment]
I just completely restarted from scratch : new immich instance, new database, everything new. I re-imported my full-library and, just for some of the videos, the issue disappeared. For the other ones the issue is still here.

**Comment by yurividal** [comment]
This issue is still present on the latest version for Android

**Comment by shenlong-tanwen** [comment]
> This issue is still present on the latest version for Android

Can you logout and log back in and check if it is reproducing again? It could still be reproducing since the current database entries are not properly linked together. However, a refresh of the app should fix those

**Comment by televoicepl** [comment]
This issue was solved in my case on new v1.132.1 release (and updated iOS app). 
Logout and logging in again is necessary.
Thank you for fixing it

**Comment by greyivy** [comment]
This is still an issue for me after logging out and in again on v1.132.1. 

![Image](https://github.com/user-attachments/assets/a6fe8425-4ee4-44a3-9ba9-aa0b4b57a9f7)

**Comment by VerTiGoEtrex** [comment]
I still get this too for some videos — I wonder if it's due to bad rotation metadata on the video?

**Comment by andreheuer** [comment]
I do have also the same issue and I think I figured out why. I have uploaded a movie taken by my iPhone using App Version 1.137.2 to Server version 1.137.3.

This is the original movie: as you can see, it was taken on November, 21st.
<img width="442" height="741" alt="Image" src="https://github.com/user-attachments/assets/759a6600-bd5e-40da-ac15-1063a0ab17e9" />

However, after uploading the movie using the backup function of the iOS app, the date changed to the upload date:

<img width="1028" height="980" alt="Image" src="https://github.com/user-attachments/assets/c9232977-c32d-4593-a807-4e45e3959108" />

Then, I checked the uploaded file using exiftool:

```
ExifTool Version Number         : 12.57
File Name                       : 2025-08-06_23:40:42.mov
Directory                       : /opt/immich/upload/library/admin/2025/2025-08
File Size                       : 47 MB
File Modification Date/Time     : 2024:11:21 21:31:16+01:00
File Access Date/Time           : 2025:08:06 23:40:59+02:00
File Inode Change Date/Time     : 2025:08:06 23:40:59+02:00
File Permissions                : -rw-------
File Type                       : MOV
File Type Extension             : mov
MIME Type                       : video/quicktime
Major Brand                     : Apple QuickTime (.MOV/QT)
Minor Version                   : 0.0.0
Compatible Brands               : qt
Movie Header Version            : 0
Create Date                     : 2025:08:06 21:40:42
Modify Date                     : 2025:08:06 21:40:52
Time Scale                      : 600
Duration                        : 14.80 s
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 7
Track Header Version            : 0
Track Create Date               : 2025:08:06 21:40:42
Track Modify Date               : 2025:08:06 21:40:52
Track ID                        : 1
Track Duration                  : 14.79 s
Track Layer                     : 0
Track Volume                    : 100.00%
Balance                         : 0
Audio Format                    : mp4a
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Purchase File Format            : mp4a
Image Width                     : 3840
Image Height                    : 2160
Clean Aperture Dimensions       : 3840x2160
Production Aperture Dimensions  : 3840x2160
Encoded Pixels Dimensions       : 3840x2160
Graphics Mode                   : ditherCopy
Op Color                        : 32768 32768 32768
Compressor ID                   : avc1
Source Image Width              : 3840
Source Image Height             : 2160
X Resolution                    : 72
Y Resolution                    : 72
Compressor Name                 : H.264
Bit Depth                       : 24
Video Frame Rate                : 30
Camera Lens Model (und-DE)      : iPhone 14 Pro back camera 6.86mm f/1.78
Camera Focal Length 35mm Equivalent (und-DE): 24
Warning                         : [minor] The ExtractEmbedded option may find more tags in the media data
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 2025:08:06 21:40:42
Media Modify Date               : 2025:08:06 21:40:52
Media Time Scale                : 600
Media Duration                  : 14.79 s
Media Language Code             : und
Gen Media Version               : 0
Gen Flags                       : 0 0 0
Gen Graphics Mode               : ditherCopy
Gen Op Color                    : 32768 32768 32768
Gen Balance                     : 0
Handler Class                   : Data Handler
Handler Vendor ID               : Apple
Handler Description             : Core Media Data Handler
Meta Format                     : mebx
Handler Type                    : Metadata Tags
Location Accuracy Horizontal    : 16.256205
Full-frame-rate-playback-intent : 1
GPS Coordinates                 : *********
Make                            : Apple
Model                           : iPhone 14 Pro
Software                        : 18.1
Creation Date                   : 2024:11:21 21:31:16+01:00
Media Data Size                 : 46645173
Media Data Offset               : 25761
Camera Lens Model               : iPhone 14 Pro back camera 6.86mm f/1.78
Camera Focal Length 35mm Equivalent: 24
Image Size                      : 3840x2160
Megapixels                      : 8.3
Avg Bitrate                     : 25.2 Mbps
GPS Altitude                    : 43.319 m
GPS Altitude Ref                : Above Sea Level
GPS Latitude                    : ****
GPS Longitude                   : ******
Rotation                        : 90
GPS Position                    : ******
```
As you can see, the correct date would be in the attribute "Creation Date", however, this is not taken.

After checking the source code, I found this part: 
https://github.com/immich-app/immich/blob/bbfff64927bb0f5138d940a65d0a3cf6fbe3bd21/server/src/services/metadata.service.ts#L35-L50

Looks like this is intended behaviour. A solution would be to change the order. But this might impact other camera using different attributes :-(

**Comment by chemicalsam** [comment]
Hope this gets fixed, driving me crazy.

**Comment by yurividal** [comment]
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/1749d967-11e3-4110-abb9-fe379fc5e7aa" />

This is still an issue on Android v1.142, even on the new beta timeline.

**Comment by alextran1502** [comment]
@yurividal looks like you need to run metadata extraction jobs for all, then after it is finished relaunch the mobile app

**Comment by yurividal** [comment]
@yurividal thank you! That did it. Fixed now

**Comment by pkrivorucko4-cell** [comment]
Hi everyone, I really need some help.
I’ve tried refreshing metadata several times and re-logging into my account, but it didn’t fix the problem.

The issue happens only on my second account and on two devices — OnePlus 10R (Android 15) and Galaxy Tab A7 Lite.
On these devices, videos are displayed incorrectly.

However, everything works perfectly on the web interface, and on my main account (Immich + Oppo Reno Lite 5), both the app and web version work fine.

I might be missing something, but I can’t figure out what’s going wrong.

![Image](https://github.com/user-attachments/assets/a38c0c4c-bf01-46f1-a4f2-28a6c2209905)
![Image](https://github.com/user-attachments/assets/257c0771-d0b9-4f48-b909-d1e1f25b7aeb)

**Comment by Snufkin-8** [comment]
I have the same issue
https://discord.com/channels/979116623879368755/1428927384635052102

Is it would be fixed?

**Comment by breejane17-boop** [comment]
1. > 

[ ] ### [/](url)

**Comment by skatsubo** [comment]
> I have the same issue [discord.com/channels/979116623879368755/1428927384635052102](https://discord.com/channels/979116623879368755/1428927384635052102)

I can reproduce ^^^ the issue reported on Discord: distorted video when playing from search results (Android, iPad app on MacOS)
- Search > By date > Select any range that contains videos > Click a video - it plays distorted
- Search > By media type > Video > Click a video - it plays distorted

In other places everything is fine. This does not happen in Timeline or when going through Search > Videos.
So in this case the asset metadata is correct, just something funky happens on the search result pages.

**Comment by goalie2002** [comment]
> > I have the same issue [discord.com/channels/979116623879368755/1428927384635052102](https://discord.com/channels/979116623879368755/1428927384635052102)
> 
> I can reproduce ^^^ the issue reported on Discord: distorted video when playing from search results (Android, iPad app on MacOS)
> 
> * Search > By date > Select any range that contains videos > Click a video - it plays distorted
> * Search > By media type > Video > Click a video - it plays distorted
> 
> In other places everything is fine. This does not happen in Timeline or when going through Search > Videos. So in this case the asset metadata is correct, just something funky happens on the search result pages.

That issue is separate from this one (#24092) and a fix is already implemented :)

**Comment by skatsubo** [comment]
> That issue is separate from this one ([#24092](https://github.com/immich-app/immich/issues/24092)) and a fix is already implemented :)

Great!
Let's see if the next release / fix for `getAspectRatio` implemented in #24131 is applicable to some cases reported in this issue.

**Comment by mat-sienczyk** [comment]
Still not fixed on latest version (both server and app 2.4.1).

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/e56b1316-c1cc-4273-9ab2-8a5261c824fb" />

**Comment by ticrz** [comment]
Hi all, 
I believe I  have identified a potential root cause for this. 
My analysis is there : https://github.com/immich-app/immich/issues/15187#issuecomment-3973192468
Please let me know how I can help. 
Best
