### ISSUE TITLE
Application issues on One UI 7

### ISSUE THREAD

**Issue by Entersjkhdfkjdhfksjf** [immich-app/immich#18255]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I recently updated my s23 from one ui 6 to 7 and every once in a while I get the "imich is not responding" error. I seems to randomly happen. It even seems to happen when running in the background 

![Image](https://github.com/user-attachments/assets/af56bbec-0f6d-4a0a-a57d-4ec3874aeed9)

### The OS that Immich Server is running on

Latest Raspberry pi os

### Version of Immich Server

V1.132.3

### Version of Immich Mobile App

V1.132.3 build 197

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value
of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference -
use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
     #  start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/ssd/immich
# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=/mnt/ssd/immich
# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=**********
# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Opened app
2. Started manual backup
3. Wait
4. Error
...

### Relevant log output

```shell

```

**Comment by SerAlbi** [comment]
I have the same issue, s24 with One UI 7

**Comment by Active1334** [comment]
I've got the same issue since yesterday on my Xiaomi

**Comment by PalmarHealer** [comment]
I have the crashing Issue aswell. Got that problem on an Samsung S10 with One UI 6.1

And I got this on my S22 Ultra with One UI 7
![Screenshot_20250513_202822_Settings.jpg](https://github.com/user-attachments/assets/66239b55-f114-4096-8901-e6395ab14eb1)

**Comment by NicholasFlamy** [comment]
You have to use your phone for a week after an update for it to relearn battery optimizations. Report back in a week and see how it is.

**Comment by NicholasFlamy** [comment]
> On my S25 with One UI 7.0, backups won't complete on the external URL. It uploads / transfers the photos, but stops on the last photo reaching 100% and does nothing more. None of the photos transferred show on the server. When I get home and the app switches local IP for the URL, it completes without issue.

Samsung f*cked up so badly with software that my friend's S24 Ultra was draining battery to 0 in only a few hours after an update and only recently an update fixed it. This is why I disabled auto-update on my Galaxy S22 on OneUI 6.1

I would suggest waiting it put and seeing if the battery optimizer is causing this issue and if it is fixed by letting it learn usage patterns.

**Comment by Entersjkhdfkjdhfksjf** [comment]
> You have to use your phone for a week after an update for it to relearn battery optimizations. Report back in a week and see how it is.
> 
> Edit: Also, OneUI 7 was temporarily paused a while ago because Samsung really screwed up in the software department.

It has been more than a week. I thought the same so I waited until now before reporting.

**Comment by Entersjkhdfkjdhfksjf** [comment]
> I have the crashing Issue aswell. Got that problem on an Samsung S10 with One UI 6.1
> 
> And I got this on my S22 Ultra with One UI 7 ![Screenshot_20250513_202822_Settings.jpg](https://github.com/user-attachments/assets/66239b55-f114-4096-8901-e6395ab14eb1)

Damn, atleast you can see it uploading. I don't even get notified.

**Comment by W1BTR** [comment]
Same issue here, S23 Ultra. Im also constantly getting a popup "Immich isnt responding" asking if I want to kill it.

**Comment by PalmarHealer** [comment]
> Same issue here, S23 Ultra. Im also constantly getting a popup "Immich isnt responding" asking if I want to kill it.

This is interesting because since I upgraded to One UI 7, I am not getting the message anymore.

**Comment by seekified** [comment]
I have this issue as well, S24+ with One UI 7. I wasn't sure if it was something to do with my phone or on the Immich side as I only updated to 1.132 quite recently.

**Comment by Entersjkhdfkjdhfksjf** [comment]
> > Same issue here, S23 Ultra. Im also constantly getting a popup "Immich isnt responding" asking if I want to kill it.
> 
> This is interesting because since I upgraded to One UI 7, I am not getting the message anymore.

That's interesting

**Comment by ITCMD** [comment]
This doesn't appear to be a server side issue as much as a cluent side issue with the apk. My guess is that as Android in general has been locking down inter-app file access, Samsung has depreciated something Immich is doing on getting files details, listing files, or the actual upload itself.

Still having the issue today. Not offering any backup at all.

**Comment by seekified** [comment]
Yes, my backups do still work. Whether it's the foreground or background one that gets the job done, I'm not sure - but files do get uploaded. The app just occasionally complains and crashes while doing it. Typically, I know a "not responding" message is on its way when Immich gives a "checking for new assets" notification that never goes away on its own.

**Comment by alextran1502** [comment]
I think this is the issue with the Issue database, as we are moving to SQLite in the coming months, this issue should be resolved on its own

**Comment by jzavalaneri** [comment]
> I think this is the issue with the Issue database, as we are moving to SQLite in the coming months, this issue should be resolved on its own

As of the latest updates. This still happens often to my wife's S25. Looks like SQLite isn't out just yet? Looking forward to it!

**Comment by W1BTR** [comment]
Still happening on the s23u as well. I'll get an "immich isnt responding" pop up to close it or wait, no matter what I press it pops up every minute or so for about ten minutes, then stops for a few hours

**Comment by zatricky** [comment]
There seems to be three issues here that are possibly related, this one, #17980, and #17026.

On my S22 Ultra, the app constantly gives the "Not Responding" warning while I'm actively scrolling the timeline when there is nothing uploading. This makes me think, whatever the problem is, it might have nothing to do with uploads - and that maybe uploads just make it more likely to happen in the first place. I already have the app set to "Unrestricted" battery also, if that were a factor.

**Comment by seekified** [comment]
FWIW I'm currently running 1.139.2 with the beta timeline enabled on my S24+ and the issue does indeed appear to be gone.

**Comment by shenlong-tanwen** [comment]
This should be fixed with the beta timeline. Please feel free to open another issue or post an update here if you still face ANRs with the new timeline.
