### ISSUE TITLE
[Beta timeline][Android] Photo details obscured by Android navigation bar in Beta timeline

### ISSUE THREAD

**Issue by Josephfilbert** [immich-app/immich#20748]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When enabling Beta timeline mode, viewing photo details that have people detected and locations will result the contents being obscured by the Android navigation buttons

### The OS that Immich Server is running on

Asustor AS5404T, running via Docker

### Version of Immich Server

v1.137.3

### Version of Immich Mobile App

v1.137.2 build 3002

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

1. Ensure Beta Timeline enabled
2. Select any photo, with either face detected or location, or both
3. Swipe up to see details
4. Swipe up until bottom, the photo-device taking details will be obscured

<details>
<summary>Unfolded</summary>

![Image](https://github.com/user-attachments/assets/7f862fa8-2b6b-4b55-b021-b33bdf9b5302)

</details>

<details>
<summary>Folded</summary>

![Image](https://github.com/user-attachments/assets/809513bd-12f0-4773-a4c4-4eb9f23585b6)

</details>

### Relevant log output

```shell

```

### Additional information

Immich Android App
Samsung Galaxy Z Fold 5

**Comment by corvy** [comment]
I have a Samsung S21 and it does not produce this error. Works just as it should.

**Comment by Josephfilbert** [comment]
This happens on Samsung Galaxy A52s (SM-A528B) too. App v1.137.2 build 3002.

<details>
<summary>Galaxy A52s</summary>

![Screenshot_20250808_082348.jpg](https://github.com/user-attachments/assets/f3cbdc93-70ec-49f1-81cd-57270c60c51b)



</details>

**Comment by Wohma** [comment]
Can confirm this issue on a Google Pixel 6a, app version 1.137.2 build 3002.

**Comment by alextran1502** [comment]
Fixed in v1.138.0

**Comment by Josephfilbert** [comment]
> Fixed in v1.138.0

I've updated to v1.138.0, however, the issue still persists.
