### ISSUE TITLE
Thumbnails and images not loading when scrolling with the timeline scrollbar even after let go on Android

### ISSUE THREAD

**Issue by waltericewhite** [immich-app/immich#23658]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When using the vertical timeline scrollbar to jump through the gallery, thumbnails and images do not load. The UI scrolls, but all media stays blank.
If I scroll normally (swiping up/down on the screen), thumbnails and images load correctly. 

I think this is a similar issue to https://github.com/immich-app/immich/issues/20542 but mine does not load or generate thumbnails even after leaving the scroll bar.

https://github.com/user-attachments/assets/044beb74-b09c-40f5-b7ce-f8f83076f3bf

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v2.2.3

### Version of Immich Mobile App

v2.2.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

OnePlus 6T Android 11

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Open the Immich Android app

2. Open the timeline view

3. Wait for the sync to complete

4. Press and hold the timeline scrollbar on the right and drag to another date

5. Observe that images and thumbnails do not load while dragging

### Relevant log output

```shell

```

### Additional information

**Expected Behavior**

Thumbnails should load dynamically while scrolling using the timeline scrollbar, just like when scrolling normally.

**Actual Behavior**

Blank placeholders appear instead of thumbnails

**Comment by bo0tzz** [comment]
Is your server running? Does the web client work?

**Comment by waltericewhite** [comment]
My server is working perfectly, you can see the sync happening when I open the app, the issue occurs only when using the timeline scrollbar not when I manually scroll down. I tested the same on the web client, it's flawless there's almost literally no delay on the web client, I think only the mobile app have this issue.

![Image](https://github.com/user-attachments/assets/e70ae120-c395-4f80-9960-d693c2833daf)

**Comment by thomasss02** [comment]
Also for me. 
Resolved with logout and login
I think the app resync everything(?)

**Comment by waltericewhite** [comment]
Issue still persists, using the vertical scrollbar to the bottom doesn't load anything, I need to manually scroll down to see it which is a huge hassle :(

**Comment by alextran1502** [comment]
Can you post the app logs after you use the scrollbar to scroll down?

**Comment by waltericewhite** [comment]
![Image](https://github.com/user-attachments/assets/235d5cfa-7455-407f-bfae-b8e55a13d7db)

![Image](https://github.com/user-attachments/assets/8e65fb1d-156c-4385-bfe1-9662bce9eb5c)

![Image](https://github.com/user-attachments/assets/d1bfa960-7f61-4253-887e-5e69a3e47121)

When I scroll normally without the scroll bar, images appear

![Image](https://github.com/user-attachments/assets/62ce31cc-9d1a-4efe-9d4f-c0948db68fe6)

**Comment by MJAvH** [comment]
Hi,

**BIG THANK's for your work with Immich!!!**

I've observed the same. If I go to Andoid app, I have sometimes the same behavour as waltericewhite - thumbnails and images do not load. Unitl now, I've not catch when exactly this arrive, with witch circumstances. 

If I go via  web client, to see the same part of galery (year & month), all works whitout any kind of delay.

On server I have still version 2.2.2, on my Android I have already version 2.2.3.

I will upgrade my server asap but I've observed this behavour with prevours version of immich on server. Here is my info about versions on server.

<img width="460" height="491" alt="Image" src="https://github.com/user-attachments/assets/f5bb0b93-1ae3-4fe4-a194-f0f06cd9f59d" />

Could be nice, that app Immich, on Android, try to keep all thumbnails whout refresh every time. Even if this will take more space on Android. Why not to add this as option in setting, to speed up display and having less trafic exchange every time when app is opened.

Best & thanks

**Comment by alextran1502** [comment]
@mertalev do you have any thoughts about this issue?

**Comment by alextran1502** [comment]
@waltericewhite are you connecting to your instance over local IP or Reverse Proxy/DNS. Do you mind helping connecting directly to local IP if not yet. if it works with local IP then we might have some insight on why it doesn't work over reverse proxy/dns

**Comment by waltericewhite** [comment]
I use caddy as reverse proxy to connect to immich, I have immich server ports closed, and adguard home for dns rewrite so that I can locally connect using `immich.mydomain.com` when I'm connected locally which points to `http://192.168.37.101:2283` and also access externally if I'm out of my network. I properly checked that when I'm connected locally immich subdomain gets resolved locally so no problem with my dns rewrites.

As you suggested,  I opened immich server ports and connected the immich mobile app using `http://192.168.37.101:2283` directly, the **issue got resolved** currently(maybe long term testing would be better). I'm not sure why it behaves weirdly using the scrollbar when using `immich.mydomain.com` both locally and externally. I'm no expert but maybe is it because https or fundamentally wrong with caddy(I'm using official immich caddy configuration btw)? Also I have static IP, just fyi no cloudflare proxy or anything.

It would be helpful resolving this before closing the issue, thanks to every immich maintainers for your work!

edit: The web client using `immich.mydomain.com` is crazy fast, no complaints there, only the mobile app freezes randomly :(
