### ISSUE TITLE
Mobile, iOS sometimes shows pink thumbnails when opening the app

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#2827]
### The bug

When I am opening the app, sometimes pink thumbnails are shown and they are there until the app is force closed and then reopened. See picture below.
I have noticed that it is only the case with already uploaded photos, if any new photos are uploaded, they show up normally.
![IMG_3241](https://github.com/immich-app/immich/assets/24546950/207c3f31-a4a4-4573-bad1-b940c1fb3bf7)

### The OS that Immich Server is running on

Ubuntu, Docker

### Version of Immich Server

v1.61.1

### Version of Immich Mobile App

v1.61.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I can provide later if needed.
```

### Your .env content

```Shell
I can provide later if needed.
```

### Reproduction steps

```bash
1.Open the app on iOS
2.Sometimes the thumbnails will show up pink
3. If there are some photos that are not yet uploaded, they will upload and show normal thumbnails
4. Force close app and reopen, the thumbnails will show up normally.
```

### Additional information

This has been bugging me for a while, it is not just the latest versions.
Also, there are no errors in the app logs.

**Comment by alextran1502** [comment]
This is Flutter bug, it will be fixed when we upload the SDK to 3.0.5, right now we are on 3.0.0

**Comment by alextran1502** [comment]
Should be fixed in recent releases

**Comment by Eldemarkki** [comment]
This is still happening on iOS 1.136.0 build.211, server 1.135.3
