### ISSUE TITLE
[BUG] Microservices crash on migration if folders mounted seperately

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#2847]
### The bug

If Immich data folders (profile, thumbs, upload, etc.) are mounted separately and any of them are empty, Immich will try to delete them which will fail.

Error:
```
[Error: EBUSY: resource busy or locked, rmdir 'upload/upload'] {
  errno: -16,
  code: 'EBUSY',
  syscall: 'rmdir',
  path: 'upload/upload'
}
```

My workaround was to add an empty file like `.no_delete_folder` which fixes the issue as the folder is not empty anymore.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.61.0

### Version of Immich Mobile App

v1.61.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${LOCATION_LIBRARY}:/usr/src/app/upload/library
      - ${LOCATION_ENCODED_VIDEO}:/usr/src/app/upload/encoded-video
      - ${LOCATION_THUMBS}:/usr/src/app/upload/thumbs
      - ${LOCATION_UPLOAD}:/usr/src/app/upload/upload
      - ${LOCATION_PROFILE}:/usr/src/app/upload/profile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      docker_local_server:
        ipv4_address: 192.168.1.x
```

### Your .env content

```Shell
LOCATION_LIBRARY=/mnt/nas_disk/...redacted...
LOCATION_ENCODED_VIDEO=./data/immich_data/encoded-video
LOCATION_THUMBS=./data/immich_data/thumbs
LOCATION_UPLOAD=./data/immich_data/upload
LOCATION_PROFILE=./data/immich_data/profile
```

### Reproduction steps

```bash
1. Mount Immich data folders separately
2. Run migration job when any of the folders are empty
3. See error in Docker logs
```

**Comment by jrasm91** [comment]
When you migrate from `YYYY-MM/DD/filename.ext` to `YYYY/MM/DD/filename.ext` for example you are going to be left with a lot of empty folders, which should be cleaned up automatically. This is true whenever the storage template changes. What we want is actually to delete empty folders _inside_ of `library/` without deleting library itself.

**Comment by jrasm91** [comment]
We used to have a different folder structure, but I think at this point we're safe to change that line to check for empty directories inside of `library/` instead of `UPLOAD_LOCATION`.

**Comment by Hawkings** [comment]
I think this was already fixed in #3059

**Comment by jrasm91** [comment]
> I think this was already fixed in #3059

I think you are right 😁

**Comment by jaimetur** [comment]
I still receive error when try to remove empty directories when I map the upload/library/user to a local volume within the homes/user like this:

      # Following lines is to use Synology home folder as destination for each Immich user:
      - /volume1/homes/jaimetur/Immich/library:/usr/src/app/upload/library/jaimetur
      - /volume1/homes/jaimetur_share/Immich/library:/usr/src/app/upload/library/jaimetur_share          
      - /volume1/homes/marasaz/Immich/library:/usr/src/app/upload/library/marasaz
      - /volume1/homes/jturcrespo/Immich/library:/usr/src/app/upload/library/jturcrespo
      - /volume1/homes/pgr1957/Immich/library:/usr/src/app/upload/library/pgr1957
      - /volume1/homes/pilukatur/Immich/library:/usr/src/app/upload/library/pilukatur
      - /volume1/homes/rafaduna/Immich/library:/usr/src/app/upload/library/rafaduna

This is the error that I got:

[Nest] 7  - 02/12/2025, 11:23:16 AM   DEBUG [Microservices:StorageTemplateService] Cleaning up empty directories...
[Nest] 7  - 02/12/2025, 11:23:17 AM   ERROR [Microservices:JobService] Unable to run job handler (storageTemplateMigration/storage-template-migration): Error: EBUSY: resource busy or locked, rmdir 'upload/library/pilukatur'
[Nest] 7  - 02/12/2025, 11:23:17 AM   ERROR [Microservices:JobService] Error: EBUSY: resource busy or locked, rmdir 'upload/library/pilukatur'
    at async Object.rmdir (node:internal/fs/promises:823:10)
    at async StorageRepository.removeEmptyDirs (/usr/src/app/dist/repositories/storage.repository.js:124:17)
    at async Promise.all (index 7)
    at async StorageRepository.removeEmptyDirs (/usr/src/app/dist/repositories/storage.repository.js:120:9)
    at async StorageTemplateService.handleMigration (/usr/src/app/dist/services/storage-template.service.js:144:9)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)

**Comment by bo0tzz** [comment]
@jaimetur this is a very old and unrelated issue. Please open a new [QA thread](https://github.com/immich-app/immich/discussions/categories/q-a)

**Comment by jaimetur** [comment]
I know is an old thread but the issue is still there. I commented it just for your info. I don't know how to open a new QA thread
