### ISSUE TITLE
[BUG] Touch on iOS app behaves in an unexpected/non-standard way

### ISSUE THREAD

**Issue by firasdib** [immich-app/immich#3101]
### The bug

First of all, thanks a lot for creating this. It’s absolutely amazing. 

With that said, I have some feedback regarding the iOS app. 

1. When zooming, the zoom happens from the center of the picture, no matter where you zoom. Also, when moving while pinching feels odd/accelerated, and not like the native app. 
2. Same goes for double tapping the image. 
3. swiping between pictures feels weird, and as if it doesnt register most of the time. 
4. swiping down to close the image viewer also is often unresponsive. 
5. when swiping between images, the old image is shown in the position of the new image for a brief moment

Overall it works, but just feels a bit off at times. Is this a native ios app or a web app wrapped in an ios shell?

thanks a lot for your hard work!

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

1.65.0

### Version of Immich Mobile App

1.65.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
n/a
```

**Comment by alextran1502** [comment]
Agree, these things bug me a lot as well. Some of the touch behaviors are odds as you describe. 

It is probably the limitation of Impeller https://docs.flutter.dev/perf/impeller

I am looking to work on improving this behavior in the future. One thing I notice though, try to make an album with one local asset and select that album as the backup album, then on the timeline, all other assets will be loaded as `remote` assets and the behavior of navigating and swiping is much nicer.

**Comment by alextran1502** [comment]
Hello is this issue still relevance? if not, can you help me close it?

**Comment by 1010010010** [comment]
Thanks for your project. I am still new to this and searched for swiping issues. This ticket describes my swiping perception as well. But there seem to exist other issues like #5895 and #4005 that could be related.

**Comment by alextran1502** [comment]
This issue has been fixed

**Comment by NicholasFlamy** [comment]
> 1. the zoom happens from the center of the picture, no matter where you zoom

This still occurs on both Android and iOS.


> But there seem to exist other issues like #5895 and #4005 that could be related.

It could be a similar component of the app but it's mostly a different issue.
