### ISSUE TITLE
[BUG] Shared albums are not being synced to mobile (android)

### ISSUE THREAD

**Issue by DriesSchaumont** [immich-app/immich#5476]
### The bug

A shared album of which I am the owner is showing up correctly on web but suddenly dissapeared from my and my parners' phone. I had the suspicion that this happened after adding new images to the album, but a database restore did not help, so I am unsure about this. This is a not a new album (it was the first one I added to Immich.)

Screenshot on phone:
![WhatsApp Image 2023-12-04 at 08 18 11](https://github.com/immich-app/immich/assets/5946712/78e793ee-9e6f-4679-8bc4-2bf21dd5f405)

Screenshot on web:
<img width="1495" alt="Screenshot 2023-12-04 at 08 14 20" src="https://github.com/immich-app/immich/assets/5946712/77e5f477-97cf-483e-ac78-1dbbf91ccf9e">

Phone logs. I retreived these after restarting the server and logging back in:
[redacted_log_mobile.csv](https://github.com/immich-app/immich/files/13543217/redacted_log_mobile.csv)

Server logs, used `docker-compose down && docker-compose up -d && docker-compose logs` for this
[server_logs.txt](https://github.com/immich-app/immich/files/13543457/server_logs.txt)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.89.0

### Version of Immich Mobile App

1.89.0 build.113

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - immich
    labels:
      traefik.enable: true
      traefik.http.routers.immich.entrypoints: 'websecure'
      traefik.http.routers.immich.rule: '**REDACTED**'
      traefik.http.routers.immich.tls: true
      traefik.http.routers.immich.tls.certresolver: '**REDACTED**'
      traefik.http.services.immich-app.loadbalancer.server.port: 3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - immich
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always
    networks:
      - immich
 redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - immich

  cloudflared:
    container_name: cloudflared_immich
    image: cloudflare/cloudflared:latest
    depends_on:
      - immich-server
    restart: always
    command: 'tunnel --no-autoupdate run --token **REDACTED**'
    networks:
      - immich

volumes:
  pgdata:
  model-cache:
  tsdata:

networks:
  immich:
    name: immich
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/nas/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=**REDACTED**
DB_PASSWORD=**REDACTED**

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
I have no idea what the original root cause is but currently I have tried the following:

1. Restarting the server
2. Restoring from a 2 week old database backup
3. Reinstalling the android client

I always wait for the 'loading' circle icon next to the 'photos' tab to finish before switching to the 'Sharing' tab. Let me know if I should run any database queries or test some other things.
```

**Comment by DriesSchaumont** [comment]
The problem seems to be with this one particular album. I created another shared album which we were able to sync. I then started to copy images from the broken album to the new one (I had to login to my partners account to copy the assets of which I was not the owner). The total number of assets in the new album is `157`, while in the old/broken album the number of assets is `158`. Could there be a duplicate entry in the database?

**Comment by shenlong-tanwen** [comment]
This should hopefully be fixed in the next version - #5465

**Comment by jrasm91** [comment]
I'm going to assume this has been fixed. Let me know if otherwise.

**Comment by DriesSchaumont** [comment]
Hi @jrasm91 Apologies for the delayed reply. I had to wait for the app to update on F-Droid to test it and this took a while. Unfortunatly I am still unable to see the album on mobile with version `1.92.1`

**Comment by JVT038** [comment]
In version 1.99.0 this problem is still present.

**Comment by DriesSchaumont** [comment]
I just noticed that the album is now showing up, although it is hard to track which change trigged that. Closing
