### ISSUE TITLE
[BUG] Backup Albums are not listed and can't be selected

### ISSUE THREAD

**Issue by SteffenAuer** [immich-app/immich#5650]
### The bug

I can't select my backup albums anymore.
Since the last update – when the iCloud photo support was introduced – I can't select the backup albums anymore. The following error is visible in the logs. On the 'Select Albums' page, the loading spinner just keeps spinning.

<img src="https://github.com/immich-app/immich/assets/60623116/b6e73c6a-bd45-4c2d-ab1e-ef978aac1b52" width=300/> <img src="https://github.com/immich-app/immich/assets/60623116/3b74a141-b205-47fc-9b30-dff2067ab7b2" width=300/> <img src="https://github.com/immich-app/immich/assets/60623116/d2931960-b050-4d5d-baea-8e7a7f7ef894" width=300/>

### The OS that Immich Server is running on

Raspbian

### Version of Immich Server

v1.88.2

### Version of Immich Mobile App

v1.90.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
_I don't have access to that atm. If still relevant, I can post it later._
```

### Your .env content

```Shell
_I don't have access to that atm. If still relevant, I can post it later._
```

### Reproduction steps

```bash
1. Launch App
2. Open the screen to select the backup albums
3. The loading spinner is the only thing visible.
```

### Additional information

I haven't update the server to the latest version yet. However, the release notes since my current version didn't indicate any requirements for the mobile version.

**Comment by alextran1502** [comment]
Can you try accessing the demo instance, it is on 1.90 and see if the issue still persist?

This issue has occurred intermittently between different users, it is on my high priority list to fix but hasn't been able to nail down the cause yet

**Comment by mjh2901** [comment]
I spent last weekend screwing with this issue on an iPhone running the latest IOS.  I can't get a listing of albums.  I finally turned off the phone's auto-lock and let it sit for a couple of hours.  nothing.  Then I went into permissions and changed the permissions so IMMICH only had access to one image.  Then it worked.  I upped to a hundred then a thousand.  When I got too far past a thousand images the problem was back.  This is a time-out problem with the app and it affects large libraries.  I have 40,000 images.  The app needs to somehow figure out albums without looking at all the images available, it also needs to work through images without again needing to know the entire scope.  As libraries get larger this problem is going to nail people.

**Comment by Chaphasilor** [comment]
I've had this issue for a few releases now (on Android 13), can't pinpoint when exactly it started. First time I open the "Select albums" screen, I get just the spinner. If I go back and open the screen again, I get the spinner and the actual album count ("Albums on device (20)", previously it said 0) after a second or so. Next time I open the screen the actual albums load, but all are unselected.

**Comment by steve5355** [comment]
I had this happen, and I can't recall how I fixed it. I think I just tried closing out and going back in toggle a few of the "background" settings under the gear menu, it eventually worked.

**Comment by SteffenAuer** [comment]
I've updated my mobile app to v1.91.0, but am still experiencing the same issue. I tried only giving permissions to Immich for a small number of assets (as mentioned above) and that does also "solve" it for me...

**Comment by thisgeekrh** [comment]
Yeah, I'm having the exact same issue. Running the newest update, with the most up to date iOS on an iPhone 15 Pro Max.

**Comment by KeeganCarter11** [comment]
I'm seeing this same behavior. Just reinstalled the Android app fresh on my wife's phone. Select an album click the back twice to get to photos then go back into backup settings and it will behave like nothing was selected. Logs don't show much of interest. Just like the setting was never picked or saved.


![Screenshot_20240109-211833](https://github.com/immich-app/immich/assets/71595294/f62f0245-79da-44b2-8fae-833d29da0059)
![Screenshot_20240109-211918](https://github.com/immich-app/immich/assets/71595294/2c0e99a1-3871-4704-9702-29ecc8dda987)
![Screenshot_20240109-211734](https://github.com/immich-app/immich/assets/71595294/2c25b326-0dc6-4f36-8574-bb93da606be4)

**Comment by AleXburnA** [comment]
I am seeing the same issue on my wife’s Android with over 18k photos locally. 
This issue could be the same: #6573

**Comment by SuperJimbo** [comment]
Seeing the same issue on an iPhone 11 running 17.2.1 with ~10k photos. It's like it's stuck in November '23 - no newer assets are loading into Immich. 

Reinstalled app, logged out, logged back in, toggled the ignore iCloud Photos option. I also tried the above trick of reducing the permissions photos on the iOS level and the back to full permissions. No change. 

Any help would be appreciated! Thanks!

**Comment by dh91779** [comment]
I see the exact same issue on iPhone 11 Pro Max iOS 17.2.1 can't see my albums after setting permissions to access all albums.

It works if I select particular files tho. 

I have a new iPhone 15 17.3.1 and don't have this issue

**Comment by R-Nabil** [comment]
Same issue on iPhone 13 Pro Max while not on iPhone 15

Weird thing is it used to show all albums. After uploading around 2000 pictures out of 14000 I'm unable to see anything...

**Comment by ednzylmz** [comment]
A hacky solution, give immich limited access and choose everything in "recents"  album. Use swipe action top left to bottom right to start scroll selecting, you can use other hand to scroll faster and select everything.

**Comment by jimeelicious** [comment]
@alextran1502 I think these issues may indeed related to iCloud. I was able to get this working completely after fiddling around with my wife's iPhone 11 (iOS v17.4.1). Her issue is a bit different where her Immich Photos library would be forever loading, nor unable to view her Immich albums or shared albums, only working with @ednzylmz's solution. Currently using the latest server build v1.105.1 as of today, her Immich iOS client is updated as well (v1.105.0 build 157). Some observations for future debugging and reference:

1) First attempted to delete ALL photos on her phone and iCloud, allowed Full access to Photo Library in the iPhone settings. Log out and in again of her Immich iOS --> issue remains. 

Library only loads successfully again if I select "No access" or "limited" access (selecting particular photos) in the iPhone settings

2) Next, I attempted to delete ALL data in iOS settings > iCloud > iCloud (again) > Photos (under "Apps using iCloud" section) > Manage storage > deleted all data --> Issue remains.

3) Next, I attempted to uncheck Shared Albums  (in iOS settings > iCloud > iCloud (again) > Photos (under "Apps using iCloud" section) > uncheck Shared Albums (under "Albums" section). --> Immich fully works as intended.

With trial #3, I was able to load her full Immich photo library, view Albums, and shared albums successfully. Furthermore, I am able to take a new photo and have it display in the photo library, and backing up as expected.

Sorry I was not able to provide any more details but wanted to contribute what I can to what is known. Hope this helps someone.

**Comment by oceanfabreeze** [comment]
@jimeelicious Your comment saved me. New iOS makes you select Full Access or select specific photos, which confused the app because all my iCloud shared albums were causing the issue. 

Immich was trying to load those albums in the app despite them not being selected as backup albums.
Turns out the immich app has a way to exclude albums by double tapping, once I did that on all the shared albums the app began working normally.  💯 

THANK YOU
