### ISSUE TITLE
[BUG] Video button disappeard on webui, ios app show an error occured.

### ISSUE THREAD

**Issue by m0eak** [immich-app/immich#5978]
### The bug

![image](https://github.com/immich-app/immich/assets/50049180/4effb599-b290-4a46-a2fc-9103e3c3b8d0)
There was a video option in the red circle before.
ios app show an error occured
![IMG_7850](https://github.com/immich-app/immich/assets/50049180/465e2d26-00f5-4819-a2f9-96e9413c3038)
![IMG_7851](https://github.com/immich-app/immich/assets/50049180/4fa72dfd-d38b-4487-a924-1ec4d8703aa4)
how can i fix it

### The OS that Immich Server is running on

unraid 6.12.6 docker

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4

### Platform with the issue

- [x] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
unraid template
```

### Your .env content

```Shell
unraid template
```

### Reproduction steps

```bash
it just happen by itself
```

**Comment by m0eak** [comment]
`#0      SearchApi.search (package:openapi/api/search_api.dart:137)
<asynchronous suspension>
#1      allVideoAssetsProvider.<anonymous closure> (package:immich_mobile/modules/search/providers/all_video_assets.provider.dart:7)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:338)
<asynchronous suspension>`

**Comment by tervillord** [comment]
Have exact same issue, i have a clean installation ,with about 2K assest. 53 vidoes.

**Comment by m0eak** [comment]
> Have exact same issue, i have a clean installation ,with about 2K assest. 53 vidoes.

I also perform a clean installation with redis and postegre, it's still happening.

**Comment by alphazhugit** [comment]
same~😔

**Comment by iiliev2** [comment]
Same issue, web and android app.

**Comment by anubis-genix** [comment]
Same bug on my setup running the latest version.

**Comment by jrasm91** [comment]
A few of the search functionalities had to be removed when we dropped typesense, but they should be added back soon (TM).

**Comment by tervillord** [comment]
> A few of the search functionalities had to be removed when we dropped typesense, but they should be added back soon (TM).

After Upgrading to new version 1.92.1,, the issue with Videos and Motion Picture is solved in app. But now for Screenshot and Selfies I have problem!
It is not loading anymore and error mention issue about network connection

**Comment by jrasm91** [comment]
The original issue with search has been solved.

**Comment by iiliev2** [comment]
The issue is not just about the underlying serach not working, but also the web UI missing the videos section. That is still not fixed in 1.114.0.
