### ISSUE TITLE
Some days in the timeline are shuffled

### ISSUE THREAD

**Issue by jenda69** [immich-app/immich#7904]
### The bug

Some older pictures (or more precisely their days) from an external library are ordered really wonky in my timeline on the web.

Note: I'll use the 07/2011 as an example in this report because that is where I first noticed this, but I can see many other months with same issue in my Immich. It also seems that at least on the web, this occurs in blocks of months - days within month are shuffled, but months are always in the correct order.

See screenshot:
![image](https://github.com/immich-app/immich/assets/932875/96807ee8-9c6d-464b-9f55-aef96cb7479f)
The screenshot is from Favorites but the main timeline does the same thing. 

Photos should be ordered from new to old, but this particular month has days displayed in order 2, 4, 3, 10, 5, 6, 16. (the 6 is cropped in the screenshot and I just noticed that 3 and 4 actually changed position when I was writing this report)
Clicking next / previous in the photo view also changes to unexpected photos. 

More in additional info.

### The OS that Immich Server is running on

Raspbian Bookworm

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION_SLOW}/upload:/usr/src/app/upload
      - ${UPLOAD_LOCATION_FAST}/upload/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION_FAST}/upload/upload:/usr/src/app/upload/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH_SLOW}/jenda/fotky:/usr/src/app/external/jenda:ro
      - ${UPLOAD_LOCATION_SLOW}/upload/library/hanka:/storage/immich/upload/library/hanka:ro
      - ${EXTERNAL_PATH_SLOW}/hanka/fotky:/usr/src/app/external/hanka:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION_SLOW}/upload:/usr/src/app/upload
      - ${UPLOAD_LOCATION_FAST}/upload/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION_FAST}/upload/upload:/usr/src/app/upload/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH_SLOW}/jenda/fotky:/usr/src/app/external/jenda:ro
      - ${UPLOAD_LOCATION_SLOW}/upload/library/hanka:/storage/immich/upload/library/hanka:ro
      - ${EXTERNAL_PATH_SLOW}/hanka/fotky:/usr/src/app/external/hanka:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION_SLOW}/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${UPLOAD_LOCATION_FAST}/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION_FAST=/storage-fast/immich
UPLOAD_LOCATION_SLOW=/storage/immich
EXTERNAL_PATH_FAST=/storage-fast/user
EXTERNAL_PATH_SLOW=/storage/user

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=IwontPostMyPasswordHere

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Open immich
2. Have photos with inconsistent Exif
3. Scroll through the timeline
4. Days are shuffled
```

### Additional information

I tried looking into the database and it seems this is similar to my issue #7178 - the only correct date/time column for the affected photos is `localDateTime`, which is also the date and time displayed in the UI.
The other fileCreated/Modified dates are from last year. Probably when I imported the library into Digikam and updated some EXIF and XMP tags for etc., it modified the modify date

I checked some photos with Exiftool:
`localDateTime` in the DB matches both _[EXIF] Date/Time Original_ and _[EXIF] Create Date_; `fileCreatedAt` & `fileModified` match _[EXIF] Modify Date_
 
If I use this query in the DB:
`SELECT * FROM "assets" WHERE "localDateTime" < '2011-08-01' AND "localDateTime" >= '2011-07-01' AND "isFavorite" = 'True' ORDER BY "fileModifiedAt" DESC`
I can see the days in the timeline are in the same order as are the first occurrences of every day in `fileModifiedAt` column. (I could probably achieve exact order using GROUP BY or something but I'm not good in SQL).

Related to that, if I open a photo and click next/prev arrow, the photos don't actually change in the order of the timeline, but in the order of the query above.

I'll post this as separate issue, but it really seems like it's the same issue as #7178 - Immich displays `localDateTime` everywhere but uses other date/time columns to actually process, sort etc. photos and these columns are not necessarily correct in my library.

I'm also fairly sure I have a related issue with the Android app. In the main timeline, days are ordered correctly there but are missing more than a half of the photos. In the favorites timeline, there's only one day for the whole month displayed (should be much more as seen on screenshot from web above). This is where I actually noticed there's something wrong in my timeline and it seems the issue occurs in the same months as the weird behaviour on the web.

**Comment by jenda69** [comment]
> Hello, just to doublecheck, do you have all your jobs finished running yet?

Yeah, no jobs are running, it's about two month since I set up Immich, only noticed this issue two days ago when I wanted show someone some old photos.

**Comment by alextran1502** [comment]
Do you mind sharing the query output so I can create dummy test data to re-create and fix it?

**Comment by alternativesurfer** [comment]
Mine does the same thing.
Installed on Ubuntu.  No tasks running.

**Comment by ArnaudCrl** [comment]
I'm also having this issue. The days in a month are not listed in the correct order.
For example I have in my timeline the 4th of may followed by the 21th of may followed by the 1st of may.
I can't see anything wrong in the jpeg metadata.

**Comment by Hixxey** [comment]
This sounds very similar to an issue I'm having.
All days in January 2024 are reversed on the timeline. So the most recent is 1st January (closest to the top) and the oldest is 31st January. 1st February 2024 and 1st January 2024 are next to each other.
This is only in the browser, it is in the correct order on mobile

**Comment by mehmooda** [comment]
https://[redacted]/api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2019-01-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true

seems to be returning assets in file system date order and not the order of the date on the asset. It then displays in that order

```js
temp1.every((e,i,v) => {return i == 0 || e.fileCreatedAt <= v[i-1].fileCreatedAt})
```
is true
```js
temp1.every((e,i,v) => {return i == 0 || e.localDateTime <= v[i-1].localDateTime})
```
is false#

so the first item in my list for Jan 2019 has
fileCreatedAt of "2019-12-29T10:08:36.477Z"
but a 
localDateTime of "2019-01-04T21:25:54.000Z"

**Comment by jenda69** [comment]
Well, since there were no updates on the issue, I used exiftool to export all dates of photos in library to csv
`exiftool -csv -csvDelim \\t -r -DateTimeOriginal -ModifyDate -FileModifyDate -CreateDate -ext jpg -ext jpeg -ext mp4 -ext mov /storage/photos/ > ./photos.csv`

Checked them in Excel and fixed DateTimeOriginal from the correct field where it was incorrect.
`exiftool -P -overwrite_original '-DateTimeOriginal<ModifyDate' [filename]`
`exiftool -P -overwrite_original '-DateTimeOriginal<filename' [directory with times in filenames]`
`exiftool -P -overwrite_original '-DateTimeOriginal<2000:01:01:12:34:56' [file where I have to make the date up]`
etc.

Then I basically let exiftool replace all dates with the correct DateTimeOriginal
`exiftool -P -r -m -overwrite_original -progress '-AllDates<DateTimeOriginal' '-FileModifyDate<DateTimeOriginal' -ext jpg -ext jpeg -ext mp4 -ext mov /storage/photos/`

In the end I refreshed the Immich library and all the photos are now ordered correctly. It also feels like clicking the scrollbar is now taking me closer to a date I clicked than before.
It was quite boring afternoon though.

**Comment by Hixxey** [comment]
> Well, since there were no updates on the issue, I used exiftool to export all dates of photos in library to csv `exiftool -csv -csvDelim \\t -r -DateTimeOriginal -ModifyDate -FileModifyDate -CreateDate -ext jpg -ext jpeg -ext mp4 -ext mov /storage/photos/ > ./photos.csv`
> 
> Checked them in Excel and fixed DateTimeOriginal from the correct field where it was incorrect. `exiftool -P -overwrite_original '-DateTimeOriginal<ModifyDate' [filename]` `exiftool -P -overwrite_original '-DateTimeOriginal<filename' [directory with times in filenames]` `exiftool -P -overwrite_original '-DateTimeOriginal<2000:01:01:12:34:56' [file where I have to make the date up]` etc.
> 
> Then I basically let exiftool replace all dates with the correct DateTimeOriginal `exiftool -P -r -m -overwrite_original -progress '-AllDates<DateTimeOriginal' '-FileModifyDate<DateTimeOriginal' -ext jpg -ext jpeg -ext mp4 -ext mov /storage/photos/`
> 
> In the end I refreshed the Immich library and all the photos are now ordered correctly. It also feels like clicking the scrollbar is now taking me closer to a date I clicked than before. It was quite boring afternoon though.

I thought it would be something along these lines, it just manifested it a slightly odd way. Do you know if the images were reimported? For example, if you favorited one of the images, then changed the date, would it remain favorited or would it be considered a new image? Just trying to figure that out before I start reprocessing them.

**Comment by jenda69** [comment]
> Do you know if the images were reimported?

I'd say if you don't change file name or directory, it should keep the favorites etc.
But I might be wrong. With my external library I also use bunch of python scripts to mark the images starred in DigiKam database as favorite, create albums from favorites in directories etc. and I don't fav anything by hand. So if these got lost, it would just mark it again.

**Comment by Hixxey** [comment]
> > Do you know if the images were reimported?
> 
> 
> 
> I'd say if you don't change file name or directory, it should keep the favorites etc.
> 
> But I might be wrong. With my external library I also use bunch of python scripts to mark the images starred in DigiKam database as favorite, create albums from favorites in directories etc. and I don't fav anything by hand. So if these got lost, it would just mark it again.

I did some testing and you're right, modifying the metadata doesn't generate a new asset in Immich.
It sounds like you're using Digikam fairly extensively, have you ever had any issues with modifying metadata from Digikam? I'm always a little nervous that changing the dates will somehow corrupt the file and I won't know until it's too late.

**Comment by unclamped** [comment]
Hey all, experimenting the same issue here. Timestamps for _some_ photos are completely wrong, in fact, a couple of vids point to the 3rd of Febuary of **2036***. Just like @jenda69 , I also used digiKam on my library prior to importing everything on immich. 
https://litter.catbox.moe/yiove2.zip

**Comment by theorician** [comment]
I'm not sure if the timestamps being incorrect is a red herring, and I don't use digiKam. I set my metadata using `exiftool`. Here's an example:

```bash
# exiftool -time:all  example.jpg
File Modification Date/Time     : 2024:07:26 14:30:36+00:00
File Access Date/Time           : 2024:07:26 14:30:36+00:00
File Inode Change Date/Time     : 2024:07:26 14:30:36+00:00
Modify Date                     : 2018:12:03 15:55:27
Date/Time Original              : 2018:12:03 15:55:27
Create Date                     : 2018:12:03 15:55:27
Offset Time Original            : -03:00
Date Time UTC                   : 0000:00:00 00:00:00
Sub Sec Time Original           : 00
GPS Time Stamp                  : 18:55:27
Time Created                    : 15:55:27-03:00
Metadata Date                   : 2020:11:02 13:21:30+01:00
Date/Time Original              : 2018:12:03 15:55:27.00-03:00
```

The only times that show 2024-07-26 are the file timestamps - exif data is fine. (the 'date time utc' is weird, though?)

Loading an album containing this image throws the 3rd of December 2018 to the very top of the timeline - above later dates - and has this photo at the very beginning of that day's list. The album most recent photo timestamp in the album list and at the top on that album's page both show 2024-07-26 as the latest photo. 

So it's something to do with the mod datetime, as https://github.com/immich-app/immich/issues/7904#issuecomment-2166803744 mehmooda says.

I have the same thing for another file:

```bash
exiftool -time:all example.png
File Modification Date/Time     : 2024:07:25 19:20:41+00:00
File Access Date/Time           : 2024:07:25 19:20:41+00:00
File Inode Change Date/Time     : 2024:07:25 19:20:41+00:00
Create Date                     : 2016:09:15 00:00:00+00:00
Modify Date                     : 2016:09:15 00:00:00
Date/Time Original              : 2016:09:15 00:00:00
```

where the exact same thing happens: the date from DateTimeOriginal or CreateDate or whatever shows at the very top, with all photos on that date listed as well, above later dates, and the 'latest photo in album' is listed as 2024-07-25. If I remove that photo, sort order and 'lasted photo in album' all return to normal.

This seems like a genuine bug in that file inode data is being used erroneously.

**Comment by jrasm91** [comment]
There are lots of date related things to discuss and fix, but the original issue about date groups being out of order has been fixed.

**Comment by theorician** [comment]
@jrasm91 In what version? Still seeing this on 1.115.0, so I don't think your statement is accurate. My description above about how some days are pulled forward in front of other days still happens.

**Comment by jrasm91** [comment]
Feel free to add a comment to #12650 and I will take a look.

**Comment by C-Otto** [comment]
I think the fix @jrasm91 meant is #12612 which is part of v.1.116.0.
