### ISSUE TITLE
Pictures recently added to external library cannot be dowloaded form the app

### ISSUE THREAD

**Issue by panoskpv** [immich-app/immich#8052]
### The bug

when I try to download a recently added picture in external library it fails. This is not the case for previously added picutres. After some investigation I realised that the ones I recently added are included in the server without file extension in their name while the ones that can be downloaded have it.
![Screenshot from 2024-03-19 00-35-40](https://github.com/immich-app/immich/assets/84382461/6f6bfe4b-8d09-4d47-b3e8-50a2e31c97eb)

![Screenshot from 2024-03-19 00-38-33](https://github.com/immich-app/immich/assets/84382461/3ab2fd1b-9b69-44f8-99e8-d6596a60903e)

However, when i click to i symbol path looks ok and filename is presented with extension.

### The OS that Immich Server is running on

Ubuntu 22.04 using docker

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

1.98.2

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
as above
```

**Comment by alextran1502** [comment]
Can you share the photos that cannot be downloaded, so that we can troubleshoot?

**Comment by panoskpv** [comment]
I do not think it is related to the photos because this happened with photos taken from two different phones at the same period. Older photos taken with same phones and previously uploaded have no issues.

**Comment by alextran1502** [comment]
Hello, just to aid in troubleshooting, having the trouble asset will help us a lot better

**Comment by panoskpv** [comment]
![IMG_20240317_104543](https://github.com/immich-app/immich/assets/84382461/ac62e193-100f-4acd-859b-4d30f7b7c368)
This is an example of photo with this issue. Also when i try to share these photos through the app the file name in the app selection pop up does notinclude extension.

**Comment by alextran1502** [comment]
Can you help zip the file up? When I tried to open the image, GitHub doesn't let me

**Comment by tiltshiftfocus** [comment]
I would like to add that I am having this issue as well on both iOS and Android. 
On iOS, sharing a photo results in no extension while on Android, i get a `.deploy` extension.

**Comment by alextran1502** [comment]
@tiltshiftfocus Thank you for the data point. So the file itself doesn't have an extension, and they are in the immich's database?

**Comment by tiltshiftfocus** [comment]
@alextran1502 The file itself has extension as updated from external library. They include JPG, HEIC, MOV, etc as seen below under `originalPath`:
<img width="527" alt="image" src="https://github.com/immich-app/immich/assets/3158046/bd419622-4c15-4c85-853a-7c2e2cb9b290">

But the extensions are missing in the `originalFileName` column:
<img width="311" alt="image" src="https://github.com/immich-app/immich/assets/3158046/0a3bab79-b7bd-4e36-b3d6-1cbeb3db314c">

This issue should have some relation to #7781 .

**Comment by alextran1502** [comment]
Hmm, so only files from the external library won't have the extension. Let me check

**Comment by alytidae** [comment]
Hi! I just started using immich today as an application to view my photos. I followed this guide (https://immich.app/docs/features/libraries /) to connect external libraries. But I have the same problem as you. If I upload a photo via the immich web version, then everything works fine for me and the photo is displayed correctly, but if I connect an external library, I can see the files, but they are all gray (there is no image on them). I can see the information about the file and all files from the external library do not have an extension. I think that's why immich can't display them.

**Comment by etnoy** [comment]
I have pushed a fix. Those who are affected, please run a refresh all files job after the fix is merged

**Comment by tiltshiftfocus** [comment]
> I have pushed a fix. Those who are affected, please run a refresh all files job after the fix is merged

I just tried in the newest version with this fix. Performing refresh all files didn't fix the extensions. Did I miss anything?

**Comment by tiltshiftfocus** [comment]
For those experienced with database queries, if you are still encountering issues with the latest update even after refreshing the files, you can use this query to update the `assets` table with the required file extension:

`UPDATE assets SET "originalFileName" = CONCAT("originalFileName",SUBSTRING("originalPath" FROM '\..*')) WHERE "originalFileName" NOT LIKE '%.%';`

Please make a backup to `assets` table before doing the above query. 
After the query, pull to refresh twice on the mobile app for the timeline to rebuild to see the changes.

**Comment by panoskpv** [comment]
I still have the same problem after refreshing. I run all stack using docker. When i connect to the database and run above command i get "relation assets does not exist". Any ideas?

**Comment by etnoy** [comment]
My bad, even a force refresh does not re-read the filename, only timestamps.

**Comment by panoskpv** [comment]
> I still have the same problem after refreshing. I run all stack using docker. When i connect to the database and run above command i get "relation assets does not exist". Any ideas?

After trying two three times it worked. Thank you for the solution.

**Comment by tiltshiftfocus** [comment]
> My bad, even a force refresh does not re-read the filename, only timestamps.

In the very least, future assets are now updated correctly 👍🏻.

**Comment by etnoy** [comment]
Yes, it appears that the file extension is not reloaded even on force refresh. Sorry! I'll reopen it until we've fixed it.

**Comment by etnoy** [comment]
This is now solved in the latest version. Rescan the library and the file name will be automatically be corrected.

Please verify that this works for you, I'll close this bug in the meantime
