### ISSUE TITLE
Android App - Missing pictures on backed up folder

### ISSUE THREAD

**Issue by CorentinGrard** [immich-app/immich#9134]
### The bug

Some pictures from the camera doesn't get replicated by immich even when the folder is selected. The pictures that doesn't get replicated doesn't seems to be different than the one that get replicated, they are all .jpg

Example:

- Show 191 pictures backed up

![image](https://github.com/immich-app/immich/assets/25911136/51b44e24-4bc4-452e-b78f-7a9d5f4e3e88)

- But there is 249 + 3 pictures that should have been backed up in total

![image](https://github.com/immich-app/immich/assets/25911136/b48a66c9-7194-4c94-80d5-00817efd0e78)

- If I open the camera folder from immich on the above pannel, I'm able to see all the pictures, even the one that aren't being backup.
- Example of picture being backup
![backup](https://github.com/immich-app/immich/assets/25911136/ece9e26f-10be-40ce-8c87-231c5b8cff15)

- Example of picture not being backup
![notbackup](https://github.com/immich-app/immich/assets/25911136/0145305b-1c17-4029-a902-defcb8efd215)

Seems to happen randomly, some pictures get replicated, other don't. 

Phone: Google Pixel 7
OS: Android 14 AP1A.240405.002
I started noticing this problem on v1.99

### The OS that Immich Server is running on

NixOS 23.05

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env.photos
    depends_on:
      - redis
      - database
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`xxxxxxxx.xxx`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls.certresolver=myresolver
      - traefik.http.services.immich.loadbalancer.server.port=3001
    networks:
      - web
      - internal

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env.photos
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - internal

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env.photos
    restart: unless-stopped
    networks:
      - web
      - internal

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: unless-stopped
    networks:
      - internal

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env.photos
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

volumes:
  model-cache:

networks:
  web:
    name: traefik_webgateway
    external: true
  internal:
    internal: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/data/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release     

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxxxxxxxxxxxxx
DB_PASSWORD=xxxxxxxxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

LOG_LEVEL=debug
```

### Reproduction steps

```bash
1. Take picture
```

### Relevant log output

```shell
2024-04-28 11:29:12.514895 | INFO     | AssetNotifier        | Load assets: 595ms |
2024-04-28 11:29:12.514851 | INFO     | AlbumService         | Syncing completed. Changes: true |
2024-04-28 11:29:12.514724 | INFO     | SyncService          | Synced changes of local album Messenger to DB |
2024-04-28 11:29:12.453612 | INFO     | SyncService          | Synced changes of local album Screenshots to DB |
2024-04-28 11:29:12.272426 | INFO     | SyncService          | Synced changes of local album Camera to DB |
2024-04-28 11:29:12.102778 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-04-28 11:29:12.102643 | INFO     | AlbumService         | Found 8 device albums |
2024-04-28 11:29:00.858534 | INFO     | AssetNotifier        | Load assets: 8238ms |
2024-04-28 11:29:00.858492 | INFO     | AlbumService         | Syncing completed. Changes: true |
2024-04-28 11:29:00.858407 | INFO     | SyncService          | Added a new local album to DB: Messenger |
2024-04-28 11:29:00.855289 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-04-28 11:29:00.757901 | INFO     | SyncService          | 0 assets already existed in DB, to upsert 1 |
2024-04-28 11:29:00.600493 | INFO     | SyncService          | Syncing a new local album to DB: Messenger |
2024-04-28 11:29:00.600412 | INFO     | SyncService          | Added a new local album to DB: Screenshots |
2024-04-28 11:29:00.598293 | INFO     | SyncService          | Upserted 10 assets into the DB |
2024-04-28 11:29:00.593914 | INFO     | SyncService          | 0 assets already existed in DB, to upsert 10 |
2024-04-28 11:29:00.554634 | INFO     | SyncService          | Syncing a new local album to DB: Screenshots |
2024-04-28 11:29:00.554522 | INFO     | SyncService          | Added a new local album to DB: Camera |
2024-04-28 11:29:00.545986 | INFO     | SyncService          | Upserted 252 assets into the DB |
2024-04-28 11:29:00.520501 | INFO     | SyncService          | 0 assets already existed in DB, to upsert 252 |
2024-04-28 11:29:00.397957 | INFO     | SyncService          | Syncing a new local album to DB: Camera |
2024-04-28 11:29:00.395207 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-04-28 11:29:00.395110 | INFO     | AlbumService         | Found 8 device albums |
2024-04-28 11:29:00.242479 | INFO     | SyncService          | Upserted 20931 assets into the DB |
2024-04-28 11:28:52.649264 | INFO     | AssetNotifier        | Manual refresh requested, cleared assets and albums from db |
2024-04-28 11:28:49.043211 | INFO     | AssetNotifier        | Load assets: 171ms |
2024-04-28 11:28:49.043052 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-04-28 11:28:49.013971 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-04-28 11:28:49.013831 | INFO     | AlbumService         | Found 8 device albums |
```

### Additional information

Tried to:
- reinstall the app
- logoff/back in
- check on an iPhone connected to the same server if something similar happen but doesn't

**Comment by FireBird4** [comment]
Same problem here

**Comment by boobin** [comment]
I have a similar issue, but in my case the photos are backed up, but the Android app still mark them as if they weren't. They don't show up on another phone using another account through shared collection. But they show up on the web page.

**Comment by alextran1502** [comment]
Probably fixed in #9149 and in the latest release https://github.com/immich-app/immich/releases/tag/v1.103.0

**Comment by CorentinGrard** [comment]
Going to try this asap, thank you @alextran1502 !

**Comment by CorentinGrard** [comment]
Fix is indeed fixed in v1.103.0 !
Closing

**Comment by FireBird4** [comment]
Updated to 1.103.1 (server and mobile)
Did not fix it for me.

Screenshot from the Album selection:
![Screenshot_2024-04-30-09-56-05-89_d8aea95ef633eb6b7eb1cae13c34b40e](https://github.com/immich-app/immich/assets/73786212/2b7d9da2-55ba-4cad-a87e-73485afb2d25)
Screenshot from the backup screen:
![Screenshot_2024-04-30-09-56-20-04_d8aea95ef633eb6b7eb1cae13c34b40e](https://github.com/immich-app/immich/assets/73786212/461d1d15-8eda-45b6-8095-bb67fd2662d3)

**Comment by boobin** [comment]
In my case, i had to uninstall/reinstall thé mobile app, but its fixed

**Comment by FireBird4** [comment]
Deleting the appdata worked.
Thank you
